import { FeaturedTeamType, LevelType } from "@/types";
import { genders, levels } from "./races";

const internalFeaturedTeams: FeaturedTeamType[] = [
  {
    name: "Air Academy (CO)",
    city: "Colorado Springs",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Austin Vandegrift (TX)",
    city: "Austin",
    state: "TX",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  { name: "Beckman", city: "Irvine", state: "CA", level: levels.sweepstakes, gender: genders.boys },
  {
    name: "Bridgeland (TX)",
    city: "Cypress",
    state: "TX",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Boulder (CO)",
    city: "Boulder",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Coeur d'Alene (ID)",
    city: "Coeur D'Alene",
    state: "ID",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Crater (OR)",
    city: "Central Point",
    state: "OR",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Crescenta Valley",
    city: "La Crescenta",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Dos Pueblos",
    city: "Goleta",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Harrison (GA)",
    city: "Kennesaw",
    state: "GA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Hart",
    city: "Santa Clarita",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Herriman (UT)",
    city: "Herriman",
    state: "UT",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Jesuit (Carmichael)",
    city: "Carmichael",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "JSerra Catholic",
    city: "San Juan Capistrano",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "La Serna",
    city: "Whittier",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Martin Luther King",
    city: "Riverside",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Matilda Torres",
    city: "Madera",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Mira Costa",
    city: "Manhattan Beach",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Mt Carmel",
    city: "San Diego",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Mountain View",
    city: "Mountain View",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Oak Park",
    city: "Oak Park",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Oak Ridge",
    city: "El Dorado Hills",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  { name: "Orem (UT)", city: "Orem", state: "UT", level: levels.sweepstakes, gender: genders.boys },
  {
    name: "Palos Verdes",
    city: "Palos Verdes Estates",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Redondo Union",
    city: "Redondo Beach",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Rock Canyon (CO)",
    city: "Highlands Ranch",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "San Clemente",
    city: "San Clemente",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  { name: "Saugus", city: "Saugus", state: "CA", level: levels.sweepstakes, gender: genders.boys },
  {
    name: "Somerset Acad Sky Pointe (NV)",
    city: "Las Vegas",
    state: "NV",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Thunder Ridge (CO)",
    city: "Highlands Ranch",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Union Catholic (NJ)",
    city: "Scotch Plains",
    state: "NJ",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Vacaville",
    city: "Vacaville",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Valencia (Valencia)",
    city: "Valencia",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Viewpoint",
    city: "Calabasas",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "West Ranch",
    city: "Stevenson Ranch",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Woodbridge",
    city: "Irvine",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  { name: "Agoura", city: "Agoura Hills", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Ayala", city: "Chino Hills", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Buchanan", city: "Clovis", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Burroughs (Ridgecrest)",
    city: "Ridgecrest",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Casteel (AZ)",
    city: "Queen Creek",
    state: "AZ",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Cathedral Catholic",
    city: "San Diego",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Claremont", city: "Claremont", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Clovis East", city: "Clovis", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Del Oro (Bakersfield)",
    city: "Bakersfield",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Eagle (ID)", city: "Eagle", state: "ID", level: levels.rated, gender: genders.boys },
  { name: "El Dorado", city: "Placentia", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "El Toro", city: "Lake Forest", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Eleanor Roosevelt (SS)",
    city: "Eastvale",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Foothill Technology",
    city: "Ventura",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Great Oak", city: "Temecula", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Harvard-Westlake",
    city: "Studio City",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Herriman (B)",
    city: "Herriman",
    state: "UT",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "La Cañada", city: "La Cañada", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Maria Carrillo",
    city: "Santa Rosa",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "McClatchy", city: "Sacramento", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Menlo School",
    city: "Atherton",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Millikan", city: "Long Beach", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Newbury Park",
    city: "Newbury Park",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Oaks Christian",
    city: "Westlake Village",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Page (AZ)", city: "Page", state: "AZ", level: levels.rated, gender: genders.boys },
  {
    name: "Ponderosa",
    city: "Shingle Springs",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Poway", city: "Poway", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Rio Mesa", city: "Oxnard", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Riverside Polytechnic",
    city: "Riverside",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Sage Creek", city: "Carlsbad", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Scripps Ranch",
    city: "San Diego",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "South Pasadena",
    city: "South Pasadena",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "St Margaret's",
    city: "San Juan Capistrano",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "St Mary's College",
    city: "Berkeley",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Tesoro", city: "Las Flores", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Trabuco Hills",
    city: "Mission Viejo",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Valley View",
    city: "Moreno Valley",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Ventura", city: "Ventura", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "West Torrance",
    city: "Torrance",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Westview", city: "San Diego", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Yucaipa", city: "Yucaipa", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Air Academy (CO)",
    city: "Colorado Springs",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Boulder (CO)",
    city: "Boulder",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Bridgeland (TX)",
    city: "Cypress",
    state: "TX",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Buchanan",
    city: "Clovis",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Canyon Crest Academy",
    city: "San Diego",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Cathedral Catholic",
    city: "San Diego",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Cherry Creek (CO)",
    city: "Greenwood Village",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Cheyenne Mountain (CO)",
    city: "Colorado Springs",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Claremont",
    city: "Claremont",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Del Norte (San Diego)",
    city: "San Diego",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Desert Hills (UT)",
    city: "St. George",
    state: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "El Toro",
    city: "Lake Forest",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Fossil Ridge",
    city: "Fort Collins",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Herriman (UT)",
    city: "Herriman",
    state: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Immanuel",
    city: "Reedley",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "JSerra Catholic",
    city: "San Juan Capistrano",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Martin Luther King",
    city: "Riverside",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Mira Costa",
    city: "Manhattan Beach",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Monte Vista",
    city: "Danville",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Mountain View",
    city: "Mountain View",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Murrieta Valley",
    city: "Murrieta",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Oak Park",
    city: "Oak Park",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Oak Ridge",
    city: "El Dorado Hills",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Orem (UT)",
    city: "Orem",
    state: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Point Loma",
    city: "San Diego",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Redwood",
    city: "Larkspur",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "San Clemente",
    city: "San Clemente",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Santa Margarita",
    city: "Rancho Santa Margarita",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Santiago (Corona)",
    city: "Corona",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  { name: "Saugus", city: "Saugus", state: "CA", level: levels.sweepstakes, gender: genders.girls },
  {
    name: "Scripps Ranch",
    city: "San Diego",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "St Francis (Sacramento)",
    city: "Sacramento",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Tesoro",
    city: "Las Flores",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Thunder Ridge (CO)",
    city: "Highlands Ranch",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Timnath (CO)",
    city: "Timnath",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Union Catholic (NJ)",
    city: "Scotch Plains",
    state: "NJ",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Wilson (Long Beach)",
    city: "Long Beach",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  { name: "Arcadia", city: "Arcadia", state: "CA", level: levels.rated, gender: genders.girls },
  { name: "Beckman", city: "Irvine", state: "CA", level: levels.rated, gender: genders.girls },
  { name: "Berkeley", city: "Berkeley", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "Big Bear",
    city: "Big Bear City",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Clovis East", city: "Clovis", state: "CA", level: levels.rated, gender: genders.girls },
  { name: "Clovis West", city: "Fresno", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "Crater (OR)",
    city: "Central Point",
    state: "OR",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Crescenta Valley",
    city: "La Crescenta",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Dos Pueblos", city: "Goleta", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "Dougherty Valley",
    city: "San Ramon",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Eagle (ID)", city: "Eagle", state: "ID", level: levels.rated, gender: genders.girls },
  {
    name: "Faith Lutheran (NV)",
    city: "Las Vegas",
    state: "NV",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Golden Valley (SJ)",
    city: "Merced",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Granada Hills",
    city: "Granada Hills",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Great Oak", city: "Temecula", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "Harvard-Westlake",
    city: "Studio City",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Holliday (TX)",
    city: "Holliday",
    state: "TX",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Huntington Beach",
    city: "Huntington Beach",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "La Jolla", city: "La Jolla", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "Laguna Beach",
    city: "Laguna Beach",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Liberty (Winchester)",
    city: "Winchester",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Long Beach Poly",
    city: "Long Beach",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Newbury Park",
    city: "Newbury Park",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Palisades Charter",
    city: "Pacific Palisades",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Palos Verdes",
    city: "Palos Verdes Estates",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Placer", city: "Auburn", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "Riverside Polytechnic",
    city: "Riverside",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Sage Creek", city: "Carlsbad", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "San Ramon Valley",
    city: "Danville",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Santa Monica",
    city: "Santa Monica",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Scripps Ranch",
    city: "San Diego",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Simi Valley",
    city: "Simi Valley",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Somerset Acad Sky Pointe (NV)",
    city: "Las Vegas",
    state: "NV",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "University (WA)",
    city: "Spokane Valley",
    state: "WA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "West Salem (OR)",
    city: "Salem",
    state: "OR",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "West Torrance",
    city: "Torrance",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Woodbridge", city: "Irvine", state: "CA", level: levels.rated, gender: genders.girls },
  { name: "Yucaipa", city: "Yucaipa", state: "CA", level: levels.rated, gender: genders.girls },
]
  .map((team, index) => ({
    ...team,
    id: index,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

function getTeamsByLevelGender(level: LevelType, gender: string) {
  return internalFeaturedTeams.filter((team) => team.level === level && team.gender === gender);
}

export const featuredTeams = {
  sweepstakesBoysTeams: getTeamsByLevelGender(levels.sweepstakes, genders.boys),
  ratedBoysTeams: getTeamsByLevelGender(levels.rated, genders.boys),
  sweepstakesGirlsTeams: getTeamsByLevelGender(levels.sweepstakes, genders.girls),
  ratedGirlsTeams: getTeamsByLevelGender(levels.rated, genders.girls),
};
