import { FeaturedIndividualType, LevelType } from "@/types";
import { genders, levels } from "@/config/races";

const internalFeaturedIndividuals: FeaturedIndividualType[] = [
  {
    firstName: "Adrian",
    lastName: "Cantu",
    teamName: "Saugus",
    teamCity: "Saugus",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Arizechukwu",
    lastName: "Nwosu",
    teamName: "Oaks Christian",
    teamCity: "Westlake Village",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Blake",
    lastName: "Bay",
    teamName: "Fresno Christian Schools",
    teamCity: "Fresno",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Brice",
    lastName: "Allen",
    teamName: "Shiloh Christian",
    teamCity: "Springdale",
    teamState: "AR",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Calvin",
    lastName: "Rivera",
    teamName: "Centennial (NV)",
    teamCity: "Las Vegas",
    teamState: "NV",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Connor",
    lastName: "Bilodeau",
    teamName: "Tahoe-Truckee",
    teamCity: "Truckee",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Derek",
    lastName: "Luna",
    teamName: "Rio Mesa",
    teamCity: "Oxnard",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Djali",
    lastName: "DeChalus",
    teamName: "St. Mary's (Berkeley)",
    teamCity: "Berkeley",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Elton",
    lastName: "Martin",
    teamName: "The Woodlands",
    teamCity: "The Woodlands",
    teamState: "TX",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Henry",
    lastName: "Hauser",
    teamName: "Menlo",
    teamCity: "Atherton",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Hugh",
    lastName: "Heyer",
    teamName: "McClatchy",
    teamCity: "Sacramento",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Jack",
    lastName: "Boland",
    teamName: "Antonian College Prep",
    teamCity: "San Antonio",
    teamState: "TX",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Jeff",
    lastName: "Hazard",
    teamName: "Northridge (UT)",
    teamCity: "Layton",
    teamState: "UT",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Landon",
    lastName: "Warriner",
    teamName: "McClatchy",
    teamCity: "Sacramento",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Michael",
    lastName: "Scarince",
    teamName: "South Pasadena",
    teamCity: "South Pasadena",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Oscar",
    lastName: "Whitely-Bermeo",
    teamName: "St. Stephens Episcopal",
    teamCity: "Austin",
    teamState: "TX",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Ruel",
    lastName: "Newberry",
    teamName: "Denton Guyer",
    teamCity: "Denton",
    teamState: "TX",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Sterling",
    lastName: "White",
    teamName: "Oaks Christian",
    teamCity: "Westlake Village",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Tyler",
    lastName: "Connelly",
    teamName: "Aledo",
    teamCity: "Aledo",
    teamState: "TX",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    firstName: "Andrew",
    lastName: "Duncan",
    teamName: "Clark (NV)",
    teamCity: "Las Vegas",
    teamState: "NV",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    firstName: "Kingsley",
    lastName: "Lin",
    teamName: "Santa Monica",
    teamCity: "Santa Monica",
    teamState: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    firstName: "Leo",
    lastName: "Brown",
    teamName: "West Linn",
    teamCity: "West Linn",
    teamState: "OR",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    firstName: "Oliver",
    lastName: "Charkiewicz",
    teamName: "River City",
    teamCity: "West Sacramento",
    teamState: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    firstName: "Rohan",
    lastName: "Iyer",
    teamName: "Milpitas",
    teamCity: "Milpitas",
    teamState: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    firstName: "Anna",
    lastName: "Furman",
    teamName: "Tri-Valley",
    teamCity: "Grahamsville",
    teamState: "NY",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Autumn",
    lastName: "Burks",
    teamName: "Tahoe-Truckee",
    teamCity: "Truckee",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Avery",
    lastName: "Barton",
    teamName: "Ogden",
    teamCity: "Ogden",
    teamState: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Bridget",
    lastName: "Smit",
    teamName: "Brighton",
    teamCity: "Cottonwood Heights",
    teamState: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Carol",
    lastName: "Dye",
    teamName: "Santa Margarita",
    teamCity: "Rancho Santa Margarita",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Elliana",
    lastName: "Patterson",
    teamName: "Christian (El Cajon)",
    teamCity: "El Cajon",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Evangeline",
    lastName: "Williams",
    teamName: "Wylie East",
    teamCity: "Wylie",
    teamState: "TX",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Farah",
    lastName: "Allen",
    teamName: "Branson",
    teamCity: "Ross",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Gelila",
    lastName: "Hailu",
    teamName: "Leigh",
    teamCity: "San Jose",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Gioia",
    lastName: "Coudriet",
    teamName: "Galena",
    teamCity: "Reno",
    teamState: "NV",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Isabella",
    lastName: "Cram",
    teamName: "Davis (UT)",
    teamCity: "Kaysville",
    teamState: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Isabella",
    lastName: "Ruiz",
    teamName: "Ontario",
    teamCity: "Ontario",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Isla",
    lastName: "Terrill",
    teamName: "Monrovia",
    teamCity: "Monrovia",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Kamilah",
    lastName: "Salim",
    teamName: "West Torrance",
    teamCity: "Torrance",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Lindsay",
    lastName: "Billotte",
    teamName: "Classical Academy",
    teamCity: "Escondido",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Maddie",
    lastName: "Carney",
    teamName: "Caldera",
    teamCity: "Bend",
    teamState: "OR",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Maddie",
    lastName: "Reeder",
    teamName: "Highland (UT)",
    teamCity: "Salt Lake City",
    teamState: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Madeleine",
    lastName: "Lane",
    teamName: "Hopkinton",
    teamCity: "Contoocook",
    teamState: "NH",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "McKenna",
    lastName: "Groen",
    teamName: "Regis Jesuit",
    teamCity: "Aurora",
    teamState: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Taryn",
    lastName: "Coulston",
    teamName: "Santa Margarita",
    teamCity: "Rancho Santa Margarita",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    firstName: "Ally",
    lastName: "Bennett",
    teamName: "Liberty (Bakersfield)",
    teamCity: "Bakersfield",
    teamState: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    firstName: "Amelia",
    lastName: "Sarkisian",
    teamName: "Brentwood School",
    teamCity: "Los Angeles",
    teamState: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    firstName: "Ashlin",
    lastName: "Mallon",
    teamName: "Cardinal Newman",
    teamCity: "Santa Rosa",
    teamState: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    firstName: "Emily",
    lastName: "Bell",
    teamName: "Rancho Cucamonga",
    teamCity: "Rancho Cucamonga",
    teamState: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    firstName: "Emmy",
    lastName: "Angelo",
    teamName: "Ponderosa",
    teamCity: "Shingle Springs",
    teamState: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    firstName: "Harper",
    lastName: "Diaz",
    teamName: "Santana",
    teamCity: "Santee",
    teamState: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    firstName: "Isabella",
    lastName: "Vasquez",
    teamName: "El Diamante",
    teamCity: "Visalia",
    teamState: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    firstName: "Kaitlyn",
    lastName: "Bitterman",
    teamName: "Mililani",
    teamCity: "Mililani",
    teamState: "HI",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    firstName: "Miley",
    lastName: "Morical",
    teamName: "Caldera",
    teamCity: "Bend",
    teamState: "OR",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    firstName: "Paula",
    lastName: "Devine",
    teamName: "St. Mary's (Berkeley)",
    teamCity: "Berkeley",
    teamState: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    firstName: "Riley",
    lastName: "Biddle",
    teamName: "Rancho Bernardo",
    teamCity: "San Diego",
    teamState: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
]
  .map((individual, index) => ({
    ...individual,
    id: index,
    name: `${individual.firstName} ${individual.lastName}`,
  }))
  .sort((a, b) => a.lastName.localeCompare(b.lastName) || a.firstName.localeCompare(b.firstName));

function getIndividualsByLevelGender(level: LevelType, gender: string) {
  return internalFeaturedIndividuals.filter(
    (individual) => individual.level === level && individual.gender === gender,
  );
}

export const featuredIndividuals = {
  sweepstakesBoysIndividuals: getIndividualsByLevelGender(levels.sweepstakes, genders.boys),
  ratedBoysIndividuals: getIndividualsByLevelGender(levels.rated, genders.boys),
  sweepstakesGirlsIndividuals: getIndividualsByLevelGender(levels.sweepstakes, genders.girls),
  ratedGirlsIndividuals: getIndividualsByLevelGender(levels.rated, genders.girls),
};
