import { FeaturedTeamType, LevelType } from "@/types";
import { genders, levels } from "@/config/races";

const internalFeaturedTeams: FeaturedTeamType[] = [
  {
    name: "Austin Vandegrift",
    city: "Austin",
    state: "TX",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  { name: "Beckman", city: "Irvine", state: "CA", level: levels.sweepstakes, gender: genders.boys },
  {
    name: "Coeur d'Alene",
    city: "Coeur d'Alene",
    state: "ID",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Crater",
    city: "Central Point",
    state: "OR",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Crescenta Valley",
    city: "La Crescenta",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Davis (UT)",
    city: "Kaysville",
    state: "UT",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Desert Hills",
    city: "Saint George",
    state: "UT",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "El Dorado",
    city: "Placentia",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  { name: "Galena", city: "Reno", state: "NV", level: levels.sweepstakes, gender: genders.boys },
  {
    name: "Granada",
    city: "Livermore",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  { name: "Hart", city: "Newhall", state: "CA", level: levels.sweepstakes, gender: genders.boys },
  {
    name: "Herriman",
    city: "Herriman",
    state: "UT",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Jesuit (Sacramento)",
    city: "Sacramento",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Mira Costa",
    city: "Manhattan Beach",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Mountain View (Mountain View)",
    city: "Mountain View",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Mt. Carmel",
    city: "San Diego",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Newbury Park",
    city: "Newbury Park",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Northfield",
    city: "Denver",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Oak Park",
    city: "Oak Park",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Plainfield South",
    city: "Plainfield",
    state: "IL",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  { name: "Poway", city: "Poway", state: "CA", level: levels.sweepstakes, gender: genders.boys },
  {
    name: "Redondo Union",
    city: "Redondo Beach",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Riverton",
    city: "Riverton",
    state: "UT",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Sage Creek",
    city: "Carlsbad",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "San Clemente",
    city: "San Clemente",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Santiago (Corona)",
    city: "Corona",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Southlake Carroll",
    city: "Southlake",
    state: "TX",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "St. John Bosco",
    city: "Bellflower",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Trabuco Hills",
    city: "Mission Viejo",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Union Catholic Regional",
    city: "Scotch Plains",
    state: "NJ",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Vacaville",
    city: "Vacaville",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Valencia (Valencia)",
    city: "Valencia",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "West Torrance",
    city: "Torrance",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Westlake (UT)",
    city: "Saratoga Springs",
    state: "UT",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Woodbridge",
    city: "Irvine",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Yucaipa",
    city: "Yucaipa",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Air Academy",
    city: "Air Force Academy",
    state: "CO",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Ayala", city: "Chino Hills", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Basha", city: "Chandler", state: "AZ", level: levels.rated, gender: genders.boys },
  { name: "Buchanan", city: "Clovis", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Burroughs (Ridgecrest)",
    city: "Ridgecrest",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Chaminade", city: "West Hills", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Claremont", city: "Claremont", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Clovis", city: "Clovis", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Clovis North", city: "Fresno", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Desert Vista (AZ)",
    city: "Phoenix",
    state: "AZ",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Dos Pueblos", city: "Goleta", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Foothill Technology (Ventura)",
    city: "Ventura",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Fullerton Union",
    city: "Fullerton",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Great Oak", city: "Temecula", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Hazel Green",
    city: "Hazel Green",
    state: "AL",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Highland (AZ)",
    city: "Gilbert",
    state: "AZ",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "La Canada", city: "La Canada", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "La Costa Canyon",
    city: "Carlsbad",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "La Serna", city: "Whittier", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Loyola", city: "Los Angeles", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "McClatchy", city: "Sacramento", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Menlo", city: "Atherton", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Menlo-Atherton",
    city: "Atherton",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Millikan", city: "Long Beach", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Milpitas", city: "Milpitas", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Murrieta Valley",
    city: "Murrieta",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Oak Ridge",
    city: "El Dorado Hills",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Redlands East Valley",
    city: "Redlands",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Redwood (Visalia)",
    city: "Visalia",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Eleanor Roosevelt",
    city: "Eastvale",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "San Juan Hills",
    city: "San Juan Capistrano",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Saugus", city: "Saugus", state: "CA", level: levels.rated, gender: genders.boys },
  { name: "Servite", city: "Anaheim", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "Somerset Sky Pointe",
    city: "Las Vegas",
    state: "NV",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "St. Margaret's Episcopal School",
    city: "San Juan Capistrano",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Temecula Valley",
    city: "Temecula",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Viewmont", city: "Bountiful", state: "UT", level: levels.rated, gender: genders.boys },
  {
    name: "Villa Park",
    city: "Villa Park",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  { name: "Warren", city: "Downey", state: "CA", level: levels.rated, gender: genders.boys },
  {
    name: "West Ranch",
    city: "Stevenson Ranch",
    state: "CA",
    level: levels.rated,
    gender: genders.boys,
  },
  {
    name: "Air Academy",
    city: "Air Force Academy",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Beckman",
    city: "Irvine",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Boulder",
    city: "Boulder",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  { name: "Branson", city: "Ross", state: "CA", level: levels.sweepstakes, gender: genders.girls },
  {
    name: "Buchanan",
    city: "Clovis",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Cathedral Catholic",
    city: "San Diego",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Claremont",
    city: "Claremont",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Crater",
    city: "Central Point",
    state: "OR",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Davis (UT)",
    city: "Kaysville",
    state: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "El Toro",
    city: "Lake Forest",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Great Oak",
    city: "Temecula",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "JSerra Catholic",
    city: "San Juan Capistrano",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Mira Costa",
    city: "Manhattan Beach",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Monte Vista (Danville)",
    city: "Danville",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Mountain View (Mountain View)",
    city: "Mountain View",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Northfield",
    city: "Denver",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Oak Park",
    city: "Oak Park",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Oak Ridge",
    city: "El Dorado Hills",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Park City",
    city: "Park CIty",
    state: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Riverton",
    city: "Riverton",
    state: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Sage Creek",
    city: "Carlsbad",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "San Clemente",
    city: "San Clemente",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "San Francisco University",
    city: "San Francisco",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Santiago (Corona)",
    city: "Corona",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Southlake Carroll",
    city: "Southlake",
    state: "TX",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "St. Francis (Sacramento)",
    city: "Sacramento",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "The Woodlands",
    city: "The Woodlands",
    state: "TX",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Timnath",
    city: "Timnath",
    state: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Union Catholic Regional",
    city: "Scotch Plains",
    state: "NJ",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Westlake (Westlake Village)",
    city: "Westlake Village",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Yorba Linda",
    city: "Yorba Linda",
    state: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Big Bear",
    city: "Big Bear City",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Cajon",
    city: "San Bernardino",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Canyon (Anaheim)",
    city: "Anaheim",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Clovis North", city: "Fresno", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "Crescenta Valley",
    city: "La Crescenta",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Desert Hills",
    city: "Saint George",
    state: "UT",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Faith Lutheran",
    city: "Las Vegas",
    state: "NV",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Fullerton Union",
    city: "Fullerton",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Golden Valley (Merced)",
    city: "Merced",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Granada", city: "Livermore", state: "CA", level: levels.rated, gender: genders.girls },
  { name: "Hart", city: "Newhall", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "Harvard-Westlake",
    city: "Studio City",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Huntington Beach",
    city: "Huntington Beach",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "La Canada", city: "La Canada", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "La Costa Canyon",
    city: "Carlsbad",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "La Serna", city: "Whittier", state: "CA", level: levels.rated, gender: genders.girls },
  { name: "Leigh", city: "San Jose", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "Wilson (Long Beach)",
    city: "Long Beach",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Mater Dei", city: "Santa Ana", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "Menlo-Atherton",
    city: "Atherton",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Mission Viejo",
    city: "Mission Viejo",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Murrieta Valley",
    city: "Murrieta",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Newbury Park",
    city: "Newbury Park",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Point Loma",
    city: "San Diego",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Poway", city: "Poway", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "Eleanor Roosevelt",
    city: "Eastvale",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Santa Margarita",
    city: "Rancho Santa Margarita",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Saugus", city: "Saugus", state: "CA", level: levels.rated, gender: genders.girls },
  {
    name: "Scripps Ranch",
    city: "San Diego",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Somerset Sky Pointe",
    city: "Las Vegas",
    state: "NV",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Taft", city: "Woodland Hills", state: "CA", level: levels.rated, gender: genders.girls },
  { name: "Tesoro", city: "Las Flores", state: "CA", level: levels.rated, gender: genders.girls },
  { name: "Timpanogos", city: "Orem", state: "UT", level: levels.rated, gender: genders.girls },
  {
    name: "Torrey Pines",
    city: "San Diego",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Trabuco Hills",
    city: "Mission Viejo",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  {
    name: "Valencia (Valencia)",
    city: "Valencia",
    state: "CA",
    level: levels.rated,
    gender: genders.girls,
  },
  { name: "Ventura", city: "Ventura", state: "CA", level: levels.rated, gender: genders.girls },
  { name: "Warren", city: "Downey", state: "CA", level: levels.rated, gender: genders.girls },
]
  .map((team, index) => ({
    ...team,
    id: index,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

function getTeamsByLevelGender(level: LevelType, gender: string) {
  return internalFeaturedTeams.filter((team) => team.level === level && team.gender === gender);
}

export const featuredTeams = {
  sweepstakesBoysTeams: getTeamsByLevelGender(levels.sweepstakes, genders.boys),
  ratedBoysTeams: getTeamsByLevelGender(levels.rated, genders.boys),
  sweepstakesGirlsTeams: getTeamsByLevelGender(levels.sweepstakes, genders.girls),
  ratedGirlsTeams: getTeamsByLevelGender(levels.rated, genders.girls),
};
