import { FeaturedIndividualType, LevelType } from "@/types";
import { genders, levels } from "./races";

const internalFeaturedIndividuals: FeaturedIndividualType[] = [
  {
    name: "Silas Aberer",
    teamName: "Burroughs (Ridgecrest)",
    teamCity: "Ridgecrest",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Brady Anderson",
    teamName: "Faith Lutheran (NV)",
    teamCity: "Las Vegas",
    teamState: "NV",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Blake Bay",
    teamName: "Fresno Christian",
    teamCity: "Fresno",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Carson Buergey",
    teamName: "Thurston (OR)",
    teamCity: "Springfield",
    teamState: "OR",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Mateo Cafaro",
    teamName: "Monte Vista",
    teamCity: "Danville",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Cooper Castleberry",
    teamName: "Poway",
    teamCity: "Poway",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Jace DeLeDonne",
    teamName: "Riverside Polytechnic",
    teamCity: "Riverside",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Ryan Fitzpatrick",
    teamName: "Nueva",
    teamCity: "San Mateo",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Tate Grabow",
    teamName: "Hill City",
    teamCity: "Hill City",
    teamState: "SD",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Henry Hauser",
    teamName: "Menlo School",
    teamCity: "Atherton",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Noel Huato",
    teamName: "Del Oro (Bakersfield)",
    teamCity: "Bakersfield",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "OIlver Hunter",
    teamName: "Dana Hills",
    teamCity: "Dana Point",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Aiden LeRoux",
    teamName: "Cheyenne Mountain, CO",
    teamCity: "Colorado Springs",
    teamState: "CO",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Andres Lomeli",
    teamName: "Kimball",
    teamCity: "Tracy",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Chase Manning",
    teamName: "Tesoro",
    teamCity: "Las Flores",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Symond Martin",
    teamName: "Page (AZ)",
    teamCity: "Page",
    teamState: "AZ",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Ashenafi McKinnis",
    teamName: "North Eugene",
    teamCity: "Eugene",
    teamState: "OR",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Mason Morical",
    teamName: "Caldera (OR)",
    teamCity: "Bend",
    teamState: "OR",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Zarian Rodriguez",
    teamName: "Hamilton (AZ)",
    teamCity: "Chandler",
    teamState: "AZ",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Marcus Salinas",
    teamName: "Clovis East",
    teamCity: "Clovis",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Noah Strohman",
    teamName: "Holliday (TX)",
    teamCity: "Holliday",
    teamState: "TX",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Kiefer Wilcox",
    teamName: "Tahoe-Truckee",
    teamCity: "Truckee",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.boys,
  },
  {
    name: "Lily Alder",
    teamName: "Timpview (UT)",
    teamCity: "Provo",
    teamState: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Ananya Balaraman",
    teamName: "North Hollywood",
    teamCity: "North Hollywood",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Amaya Bharadwaj",
    teamName: "Palo Alto",
    teamCity: "Palo Alto",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Avery Barton",
    teamName: "Ogden",
    teamCity: "Ogden",
    teamState: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Chiara Dailey",
    teamName: "La Jolla",
    teamCity: "La Jolla",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Brynn Davenport",
    teamName: "Crater (OR)",
    teamCity: "Central Point",
    teamState: "OR",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Harper Diaz",
    teamName: "Santana (San Diego)",
    teamCity: "Santee",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Taylor Drewry",
    teamName: "Basha (AZ)",
    teamCity: "Chandler",
    teamState: "AZ",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Sophia Grant",
    teamName: "Newbury Park",
    teamCity: "Newbury Park",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Adria Favero",
    teamName: "Olympus, UT",
    teamCity: "Holladay",
    teamState: "UT",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Audrey Heath",
    teamName: "Capistrano Valley",
    teamCity: "Mission Viejo",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Ayanna Hickey",
    teamName: "The Bishop's School",
    teamCity: "La Jolla",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Charlotte Hopkins",
    teamName: "Arcadia",
    teamCity: "Arcadia",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Ashlin Mallon",
    teamName: "Cardinal Newman",
    teamCity: "Santa Rosa",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Payton Meineke",
    teamName: "Riverdale Ridge (CO)",
    teamCity: "Thornton",
    teamState: "CO",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Carina Nottingham",
    teamName: "Berkeley",
    teamCity: "Berkeley",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Becky Osorio",
    teamName: "West Covina",
    teamCity: "West Covina",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Avery Peck",
    teamName: "Long Beach Poly",
    teamCity: "Long Beach",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Isabella Ramirez",
    teamName: "Bullard",
    teamCity: "Fresno",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Giselle Fernandez",
    teamName: "Riverbank",
    teamCity: "Riverbank",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Amelia Sarkisian",
    teamName: "Brentwood School",
    teamCity: "Los Angeles",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Jaelyn Williams",
    teamName: "Eastlake",
    teamCity: "Chula Vista",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Summer Wilson",
    teamName: "Irvine",
    teamCity: "Irvine",
    teamState: "CA",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
  {
    name: "Macy Wingard",
    teamName: "Denton Braswell",
    teamCity: "Aubrey",
    teamState: "TX",
    level: levels.sweepstakes,
    gender: genders.girls,
  },
]
  .map((individual, index) => ({
    ...individual,
    id: index,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));

function getIndividualsByLevelGender(level: LevelType, gender: string) {
  return internalFeaturedIndividuals.filter(
    (individual) => individual.level === level && individual.gender === gender,
  );
}

export const featuredIndividuals = {
  sweepstakesBoysIndividuals: getIndividualsByLevelGender(levels.sweepstakes, genders.boys),
  sweepstakesGirlsIndividuals: getIndividualsByLevelGender(levels.sweepstakes, genders.girls),
};
