import { ParticipatingTeamType } from "@/types";
import { divisions, heats } from "@/config/races";

export const participatingTeams: ParticipatingTeamType[] = [
  {
    name: "ALA - Gilbert North",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Gilbert",
    state: "AZ",
  },
  {
    name: "Anaheim",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Anaheim",
    state: "CA",
  },
  {
    name: "Apple Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Apple Valley",
    state: "CA",
  },
  {
    name: "Arbor View",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Arroyo (El Monte)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "El Monte",
    state: "CA",
  },
  {
    name: "Bellflower",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Bellflower",
    state: "CA",
  },
  {
    name: "Brea Olinda",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Brea",
    state: "CA",
  },
  {
    name: "Buena (Ventura)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Ventura",
    state: "CA",
  },
  {
    name: "Buena Park",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Buena Park",
    state: "CA",
  },
  {
    name: "Burbank",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Burbank",
    state: "CA",
  },
  {
    name: "Calabasas",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Calabasas",
    state: "CA",
  },
  {
    name: "Carondelet",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Concord",
    state: "CA",
  },
  {
    name: "Carter",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Rialto",
    state: "CA",
  },
  {
    name: "Centennial (Corona)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Corona",
    state: "CA",
  },
  {
    name: "Centennial (Bakersfield)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Cerritos",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Cerritos",
    state: "CA",
  },
  {
    name: "Channel Islands",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Oxnard",
    state: "CA",
  },
  {
    name: "Clark (NV)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Coachella Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Thermal",
    state: "CA",
  },
  {
    name: "Coconino",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Flagstaff",
    state: "AZ",
  },
  {
    name: "Colton",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Colton",
    state: "CA",
  },
  {
    name: "Deer Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Glendale",
    state: "AZ",
  },
  {
    name: "Del Sol",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Oxnard",
    state: "CA",
  },
  {
    name: "Diamond Ranch",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Pomona",
    state: "CA",
  },
  {
    name: "Downey",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Downey",
    state: "CA",
  },
  {
    name: "Eastside",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Lancaster",
    state: "CA",
  },
  {
    name: "El Camino (Oceanside)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Oceanside",
    state: "CA",
  },
  {
    name: "El Capitan (Lakeside)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Lakeside",
    state: "CA",
  },
  {
    name: "El Diamante",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Visalia",
    state: "CA",
  },
  {
    name: "El Modena",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Orange",
    state: "CA",
  },
  {
    name: "Elsinore",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Wildomar",
    state: "CA",
  },
  {
    name: "Escondido",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Escondido",
    state: "CA",
  },
  {
    name: "Foothill (NV)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Henderson",
    state: "NV",
  },
  {
    name: "Fullerton Union",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Fullerton",
    state: "CA",
  },
  {
    name: "Gabrielino",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "San Gabriel",
    state: "CA",
  },
  {
    name: "Garden Grove",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Garden Grove",
    state: "CA",
  },
  {
    name: "Glen A. Wilson (Hacienda Heights)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Hacienda Heights",
    state: "CA",
  },
  {
    name: "Glendale",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Glendale",
    state: "CA",
  },
  {
    name: "Godinez",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Grand Terrace",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Grand Terrace",
    state: "CA",
  },
  {
    name: "Green Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Henderson",
    state: "NV",
  },
  {
    name: "Highland (Bakersfield)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Hillcrest",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Imperial",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Imperial",
    state: "CA",
  },
  {
    name: "Irvine",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "Kaiser",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Fontana",
    state: "CA",
  },
  {
    name: "Katella",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Orange",
    state: "CA",
  },
  {
    name: "Kennedy (La Palma)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "La Palma",
    state: "CA",
  },
  {
    name: "La Habra",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "La Habra",
    state: "CA",
  },
  {
    name: "La Mirada",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "La Mirada",
    state: "CA",
  },
  {
    name: "La Quinta (Westminster)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Westminster",
    state: "CA",
  },
  {
    name: "Littlerock",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Littlerock",
    state: "CA",
  },
  {
    name: "Loyola",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Marshall Fundamental",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Pasadena",
    state: "CA",
  },
  {
    name: "Mater Dei",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Merced",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Merced",
    state: "CA",
  },
  {
    name: "Meridian",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Meridian",
    state: "ID",
  },
  {
    name: "Mililani",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Mililani",
    state: "HI",
  },
  {
    name: "Mission Viejo",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Mission Viejo",
    state: "CA",
  },
  {
    name: "Moreno Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Moreno Valley",
    state: "CA",
  },
  {
    name: "Nogales",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "La Puente",
    state: "CA",
  },
  {
    name: "North Bakersfield",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "North Torrance",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Torrance",
    state: "CA",
  },
  {
    name: "Northwood",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "Oceanside",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Oceanside",
    state: "CA",
  },
  {
    name: "Ontario",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Ontario",
    state: "CA",
  },
  {
    name: "Orange",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Orange",
    state: "CA",
  },
  {
    name: "Orange Vista",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Perris",
    state: "CA",
  },
  {
    name: "Oxnard",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Oxnard",
    state: "CA",
  },
  {
    name: "Paloma Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Menifee",
    state: "CA",
  },
  {
    name: "Palos Verdes",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Palos Verdes Estates",
    state: "CA",
  },
  {
    name: "Patterson",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Patterson",
    state: "CA",
  },
  {
    name: "Point Loma",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Porterville",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Porterville",
    state: "CA",
  },
  {
    name: "Portola",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "Queen Creek",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Queen Creek",
    state: "AZ",
  },
  {
    name: "Ramona (Riverside)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Rancho Buena Vista",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Vista",
    state: "CA",
  },
  {
    name: "Redlands",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Redlands",
    state: "CA",
  },
  {
    name: "Redlands East Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Redlands",
    state: "CA",
  },
  {
    name: "Reedley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Reedley",
    state: "CA",
  },
  {
    name: "Righetti",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Santa Maria",
    state: "CA",
  },
  {
    name: "Rio Americano",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Sacramento",
    state: "CA",
  },
  {
    name: "Rio Mesa",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Oxnard",
    state: "CA",
  },
  {
    name: "Robert F Kennedy",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Delano",
    state: "CA",
  },
  {
    name: "Roosevelt",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Rowland Heights",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Rowland Heights",
    state: "CA",
  },
  {
    name: "San Diego",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Santa Ana Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Santa Fe",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Santa Fe Springs",
    state: "CA",
  },
  {
    name: "Santa Monica",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Santa Monica",
    state: "CA",
  },
  {
    name: "Santa Paula",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Santa Paula",
    state: "CA",
  },
  {
    name: "Santana",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Santee",
    state: "CA",
  },
  {
    name: "Santee EC",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Santiago (Garden Grove)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Garden Grove",
    state: "CA",
  },
  {
    name: "Savanna",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Anaheim",
    state: "CA",
  },
  {
    name: "Serrano",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Phelan",
    state: "CA",
  },
  {
    name: "Shadow Hills",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Indio",
    state: "CA",
  },
  {
    name: "Shafter",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Shafter",
    state: "CA",
  },
  {
    name: "Sonora (La Habra)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "La Habra",
    state: "CA",
  },
  {
    name: "South Hills",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "West Covina",
    state: "CA",
  },
  {
    name: "Sunny Hills",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Fullerton",
    state: "CA",
  },
  {
    name: "Tahquitz",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Hemet",
    state: "CA",
  },
  {
    name: "Thousand Oaks",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Thousand Oaks",
    state: "CA",
  },
  {
    name: "Torrance",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Torrance",
    state: "CA",
  },
  {
    name: "Tustin",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Tustin",
    state: "CA",
  },
  {
    name: "Valencia (Placentia)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Placentia",
    state: "CA",
  },
  {
    name: "Vista Del Lago",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Moreno Valley",
    state: "CA",
  },
  {
    name: "Vista",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Vista",
    state: "CA",
  },
  {
    name: "West Hills",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Santee",
    state: "CA",
  },
  {
    name: "West Torrance",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Torrance",
    state: "CA",
  },
  {
    name: "West Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Hemet",
    state: "CA",
  },
  {
    name: "Westminster",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Westminster",
    state: "CA",
  },
  {
    name: "Will C. Wood",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Vacaville",
    state: "CA",
  },
  {
    name: "Wiseburn Da Vinci",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "El Segundo",
    state: "CA",
  },
  {
    name: "Woodside",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Woodside",
    state: "CA",
  },
  {
    name: "Xavier College Prep",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Academy of Careers and Exploration",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Helendale",
    state: "CA",
  },
  {
    name: "ALA - Queen Creek",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Queen Creek",
    state: "AZ",
  },
  {
    name: "Ambassador Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Torrance",
    state: "CA",
  },
  {
    name: "Anthem Prep",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Antonian College Prep",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Antonio",
    state: "TX",
  },
  {
    name: "Arcadia Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Arcadia",
    state: "CA",
  },
  {
    name: "Arete Preparatory Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Gilbert",
    state: "AZ",
  },
  {
    name: "Ashland",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Ashland",
    state: "OR",
  },
  {
    name: "Banning",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Banning",
    state: "CA",
  },
  {
    name: "Belmont",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Big Bear",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Big Bear City",
    state: "CA",
  },
  {
    name: "Bishop Amat",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "La Puente",
    state: "CA",
  },
  {
    name: "Campbell Hall",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Studio City",
    state: "CA",
  },
  {
    name: "Cantwell Sacred Heart of Mary",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Montebello",
    state: "CA",
  },
  {
    name: "Canyon Hills",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Central",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Central City Value",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Chadwick School",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Palos Verdes Peninsula",
    state: "CA",
  },
  {
    name: "Chandler Prep",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Chandler",
    state: "AZ",
  },
  {
    name: "Clairemont",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Classical Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Escondido",
    state: "CA",
  },
  {
    name: "Colfax",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Colfax",
    state: "CA",
  },
  {
    name: "Community Charter",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Lake View Terrace",
    state: "CA",
  },
  {
    name: "Corvallis",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Corvallis",
    state: "OR",
  },
  {
    name: "Crawford",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Crean Lutheran",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "Crismon Queen Creek (AZ)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Queen Creek",
    state: "AZ",
  },
  {
    name: "Damien",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "La Verne",
    state: "CA",
  },
  {
    name: "Del Lago Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Escondido",
    state: "CA",
  },
  {
    name: "Desert Christian (Lancaster)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Lancaster",
    state: "CA",
  },
  {
    name: "Desert (Edwards)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Edwards",
    state: "CA",
  },
  {
    name: "Dinuba",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Dinuba",
    state: "CA",
  },
  {
    name: "Don Bosco Tech",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Rosemead",
    state: "CA",
  },
  {
    name: "Enumclaw",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Enumclaw",
    state: "WA",
  },
  {
    name: "Estancia",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Costa Mesa",
    state: "CA",
  },
  {
    name: "Flintridge Prep",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "La Canada Flintridge",
    state: "CA",
  },
  {
    name: "Flintridge Sacred Heart",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "La Canada",
    state: "CA",
  },
  {
    name: "Fresno Christian Schools",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Girls Academic Leadership Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Glendale Preparatory Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Peoria",
    state: "AZ",
  },
  {
    name: "Great Hearts Anthem Prep",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Hanalani Schools",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Mililani",
    state: "HI",
  },
  {
    name: "Harker",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Jose",
    state: "CA",
  },
  {
    name: "Hawthorne Math and Science Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Hawthorne",
    state: "CA",
  },
  {
    name: "Healdsburg",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Healdsburg",
    state: "CA",
  },
  {
    name: "Heritage Academy Gateway",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Queen Creek",
    state: "AZ",
  },
  {
    name: "Heritage Christian (Northridge)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Northridge",
    state: "CA",
  },
  {
    name: "High Tech High Mesa",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Holtville",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Holtville",
    state: "CA",
  },
  {
    name: "Hopi",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Keams Canyon",
    state: "AZ",
  },
  {
    name: "Hughson",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Hughson",
    state: "CA",
  },
  {
    name: "Hurricane Tigers",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Hurricane",
    state: "UT",
  },
  {
    name: "International School of Los Angeles",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Burbank",
    state: "CA",
  },
  {
    name: "Kingman Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Kingman",
    state: "AZ",
  },
  {
    name: "La Jolla Country Day",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "La Jolla",
    state: "CA",
  },
  {
    name: "La Salle",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Pasadena",
    state: "CA",
  },
  {
    name: "Laguna Beach",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Laguna Beach",
    state: "CA",
  },
  {
    name: "Linfield Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Temecula",
    state: "CA",
  },
  {
    name: "Los Amigos",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Fountain Valley",
    state: "CA",
  },
  {
    name: "Lucerne Valley",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Lucerne Valley",
    state: "CA",
  },
  {
    name: "Mammoth",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Mammoth Lakes",
    state: "CA",
  },
  {
    name: "Maranatha",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Pasadena",
    state: "CA",
  },
  {
    name: "Mary Star of the Sea",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "San Pedro",
    state: "CA",
  },
  {
    name: "Mayfield",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Pasadena",
    state: "CA",
  },
  {
    name: "Middle College",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Minarets",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "O'Neals",
    state: "CA",
  },
  {
    name: "Mission Vista",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Oceanside",
    state: "CA",
  },
  {
    name: "Mountain View (El Monte)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "El Monte",
    state: "CA",
  },
  {
    name: "New West Charter",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Northview",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Covina",
    state: "CA",
  },
  {
    name: "Northwest Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Notre Dame (Riverside)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Notre Dame (Sherman Oaks)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Sherman Oaks",
    state: "CA",
  },
  {
    name: "Nueva (San Mateo)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "San Mateo",
    state: "CA",
  },
  {
    name: "Oaks Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Westlake Village",
    state: "CA",
  },
  {
    name: "Ocean View",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Huntington Beach",
    state: "CA",
  },
  {
    name: "Ontario Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Ontario",
    state: "CA",
  },
  {
    name: "Oxford Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Cypress",
    state: "CA",
  },
  {
    name: "Pacific",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Bernardino",
    state: "CA",
  },
  {
    name: "Pacifica Christian (Newport Beach)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Newport Beach",
    state: "CA",
  },
  {
    name: "Pasadena",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Pasadena",
    state: "CA",
  },
  {
    name: "Pinole Valley",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Pinole",
    state: "CA",
  },
  {
    name: "Pomona Catholic",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Pomona",
    state: "CA",
  },
  {
    name: "Rancho Alamitos",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Garden Grove",
    state: "CA",
  },
  {
    name: "Rim of the World",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Lake Arrowhead",
    state: "CA",
  },
  {
    name: "Riverbank",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Riverbank",
    state: "CA",
  },
  {
    name: "Sacramento Adventist",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Carmichael",
    state: "CA",
  },
  {
    name: "Sacred Heart",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Saint Bonaventure",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Ventura",
    state: "CA",
  },
  {
    name: "Saint Jeanne de Lestonnac",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Temecula",
    state: "CA",
  },
  {
    name: "Samueli Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "San Bernardino",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Bernardino",
    state: "CA",
  },
  {
    name: "San Domenico",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "San Anselmo",
    state: "CA",
  },
  {
    name: "San Gabriel Mission",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "San Gabriel",
    state: "CA",
  },
  {
    name: "San Jacinto Valley Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "San Jacinto",
    state: "CA",
  },
  {
    name: "San Marin",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Novato",
    state: "CA",
  },
  {
    name: "Santa Clara",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Oxnard",
    state: "CA",
  },
  {
    name: "Santa Fe Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Solana Beach",
    state: "CA",
  },
  {
    name: "Santa Rosa Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Menifee",
    state: "CA",
  },
  {
    name: "St. Monica Prep",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Santa Monica",
    state: "CA",
  },
  {
    name: "St. Paul",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Santa Fe Springs",
    state: "CA",
  },
  {
    name: "St. Stephens Episcopal",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Austin",
    state: "TX",
  },
  {
    name: "St. Lucy's",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Glendora",
    state: "CA",
  },
  {
    name: "St. Margaret's Episcopal School",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "San Juan Capistrano",
    state: "CA",
  },
  {
    name: "St. Mary's (Berkeley)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Berkeley",
    state: "CA",
  },
  {
    name: "St. Monica Academy (Montrose)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Montrose",
    state: "CA",
  },
  {
    name: "Stella Charter Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Sun Valley Magnet",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Sun Valley",
    state: "CA",
  },
  {
    name: "Temecula Preparatory School",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Winchester",
    state: "CA",
  },
  {
    name: "Terra Linda",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Rafael",
    state: "CA",
  },
  {
    name: "Thacher School",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Ojai",
    state: "CA",
  },
  {
    name: "The Bishop's School",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "La Jolla",
    state: "CA",
  },
  {
    name: "Trinity Classical Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Valencia",
    state: "CA",
  },
  {
    name: "Union Catholic Regional",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Scotch Plains",
    state: "NJ",
  },
  {
    name: "Union Mine",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "El Dorado",
    state: "CA",
  },
  {
    name: "United Christian Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Rancho Cucamonga",
    state: "CA",
  },
  {
    name: "University Prep (Redding)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Redding",
    state: "CA",
  },
  {
    name: "Verrado",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Buckeye",
    state: "AZ",
  },
  {
    name: "Valor Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "North Hills",
    state: "CA",
  },
  {
    name: "Viewpoint",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Calabasas",
    state: "CA",
  },
  {
    name: "Virgin Valley",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Mesquite",
    state: "NV",
  },
  {
    name: "Webb",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Claremont",
    state: "CA",
  },
  {
    name: "West Point Grey Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Vancouver",
    state: "BC",
  },
  {
    name: "Westridge School",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Pasadena",
    state: "CA",
  },
  {
    name: "Whitney (Cerritos)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Cerritos",
    state: "CA",
  },
  {
    name: "Whittier Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "La Habra",
    state: "CA",
  },
  {
    name: "Windward School",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Woodcrest Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Yosemite",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Oakhurst",
    state: "CA",
  },
  {
    name: "Basic",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Henderson",
    state: "NV",
  },
  {
    name: "Compton Early College",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Compton",
    state: "CA",
  },
  {
    name: "Los Altos",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Hacienda Heights",
    state: "CA",
  },
  {
    name: "Royal",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Simi Valley",
    state: "CA",
  },
  {
    name: "Granite Hills",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Apple Valley",
    state: "CA",
  },
  {
    name: "University Prep (Victorville)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Victorville",
    state: "CA",
  },
  {
    name: "Alisal",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Salinas",
    state: "CA",
  },
  {
    name: "Aliso Niguel",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Aliso Viejo",
    state: "CA",
  },
  {
    name: "Alta Loma",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Alta Loma",
    state: "CA",
  },
  {
    name: "American",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Fremont",
    state: "CA",
  },
  {
    name: "Arcadia",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Arcadia",
    state: "CA",
  },
  {
    name: "Austin Vandegrift",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Austin",
    state: "TX",
  },
  {
    name: "Ayala",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Chino Hills",
    state: "CA",
  },
  {
    name: "Bakersfield",
    raceDay: "Saturday Morning",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Basha",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Chandler",
    state: "AZ",
  },
  {
    name: "Beaumont",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Beaumont",
    state: "CA",
  },
  {
    name: "Beckman",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "Brighton",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Cottonwood Heights",
    state: "UT",
  },
  {
    name: "Buchanan",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Clovis",
    state: "CA",
  },
  {
    name: "Bullard",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Cajon",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Bernardino",
    state: "CA",
  },
  {
    name: "California (Whittier)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Whittier",
    state: "CA",
  },
  {
    name: "Camarillo",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Camarillo",
    state: "CA",
  },
  {
    name: "Canyon (Anaheim)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Anaheim",
    state: "CA",
  },
  {
    name: "Canyon Crest Academy",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Canyon Springs",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Moreno Valley",
    state: "CA",
  },
  {
    name: "Carlmont",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Belmont",
    state: "CA",
  },
  {
    name: "Carlsbad",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Carlsbad",
    state: "CA",
  },
  {
    name: "Carson",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Carson City",
    state: "NV",
  },
  {
    name: "Castro Valley",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Castro Valley",
    state: "CA",
  },
  {
    name: "Centennial (NV)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Chaffey",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Ontario",
    state: "CA",
  },
  {
    name: "Chaparral",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Temecula",
    state: "CA",
  },
  {
    name: "Chino Hills",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Chino Hills",
    state: "CA",
  },
  {
    name: "Cleveland",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Reseda",
    state: "CA",
  },
  {
    name: "Clovis East",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Clovis",
    state: "CA",
  },
  {
    name: "Clovis North",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Crescenta Valley",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "La Crescenta",
    state: "CA",
  },
  {
    name: "Cypress",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Cypress",
    state: "CA",
  },
  {
    name: "Del Oro (Bakersfield)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Desert Oasis",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Desert Vista (AZ)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Diamond Bar",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Diamond Bar",
    state: "CA",
  },
  {
    name: "Dos Pueblos",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Goleta",
    state: "CA",
  },
  {
    name: "Dougherty Valley",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Ramon",
    state: "CA",
  },
  {
    name: "Eastlake",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Chula Vista",
    state: "CA",
  },
  {
    name: "Edison",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Eleanor Roosevelt",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Eastvale",
    state: "CA",
  },
  {
    name: "Etiwanda",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Rancho Cucamonga",
    state: "CA",
  },
  {
    name: "Fontana",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Fontana",
    state: "CA",
  },
  {
    name: "Fountain Valley",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Fountain Valley",
    state: "CA",
  },
  {
    name: "Great Oak",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Temecula",
    state: "CA",
  },
  {
    name: "Grossmont",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "El Cajon",
    state: "CA",
  },
  {
    name: "Hamilton (Los Angeles)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Hamilton (AZ)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Chandler",
    state: "AZ",
  },
  {
    name: "Helix",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "La Mesa",
    state: "CA",
  },
  {
    name: "Hemet",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Hemet",
    state: "CA",
  },
  {
    name: "Herriman",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Herriman",
    state: "UT",
  },
  {
    name: "Hesperia",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Hesperia",
    state: "CA",
  },
  {
    name: "Highland (AZ)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Gilbert",
    state: "AZ",
  },
  {
    name: "Higley",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Gilbert",
    state: "AZ",
  },
  {
    name: "Homestead",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Cupertino",
    state: "CA",
  },
  {
    name: "Huntington Beach",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Huntington Beach",
    state: "CA",
  },
  {
    name: "Lancaster",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Lancaster",
    state: "CA",
  },
  {
    name: "Lewisville Flower Mound",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Flower Mound",
    state: "TX",
  },
  {
    name: "Liberty (Winchester)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Winchester",
    state: "CA",
  },
  {
    name: "Liberty (NV)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Henderson",
    state: "NV",
  },
  {
    name: "Liberty (Bakersfield)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Long Beach Poly",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Long Beach",
    state: "CA",
  },
  {
    name: "Los Alamitos",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Los Alamitos",
    state: "CA",
  },
  {
    name: "Marana",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Marana",
    state: "AZ",
  },
  {
    name: "Menlo-Atherton",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Atherton",
    state: "CA",
  },
  {
    name: "Millikan",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Long Beach",
    state: "CA",
  },
  {
    name: "Milpitas",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Milpitas",
    state: "CA",
  },
  {
    name: "Mira Costa",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Manhattan Beach",
    state: "CA",
  },
  {
    name: "Mission Hills",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Marcos",
    state: "CA",
  },
  {
    name: "Monte Vista (Danville)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Danville",
    state: "CA",
  },
  {
    name: "Mountain Ridge",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Glendale",
    state: "AZ",
  },
  {
    name: "Murrieta Valley",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Murrieta",
    state: "CA",
  },
  {
    name: "Oak Hills",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Hesperia",
    state: "CA",
  },
  {
    name: "Oak Ridge",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "El Dorado Hills",
    state: "CA",
  },
  {
    name: "Orange County School of the Arts",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Otay Ranch",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Chula Vista",
    state: "CA",
  },
  {
    name: "Paramount",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Paramount",
    state: "CA",
  },
  {
    name: "Patrick Henry",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Perry",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Gilbert",
    state: "AZ",
  },
  {
    name: "Pioneer Valley",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Santa Maria",
    state: "CA",
  },
  {
    name: "Plainfield South",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Plainfield",
    state: "IL",
  },
  {
    name: "Poly (Riverside)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Rancho Bernardo",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Rancho Cucamonga",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Rancho Cucamonga",
    state: "CA",
  },
  {
    name: "Redondo Union",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Redondo Beach",
    state: "CA",
  },
  {
    name: "Redwood (Visalia)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Visalia",
    state: "CA",
  },
  {
    name: "Ridgeview",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Riverton",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Riverton",
    state: "UT",
  },
  {
    name: "Rock Canyon",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Highlands Ranch",
    state: "CO",
  },
  {
    name: "San Clemente",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Clemente",
    state: "CA",
  },
  {
    name: "San Juan Hills",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Juan Capistrano",
    state: "CA",
  },
  {
    name: "San Leandro",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "San Leandro",
    state: "CA",
  },
  {
    name: "San Marcos",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Marcos",
    state: "CA",
  },
  {
    name: "Sanger",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Sanger",
    state: "CA",
  },
  {
    name: "Santa Ana",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Santa Maria",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Santa Maria",
    state: "CA",
  },
  {
    name: "Santiago (Corona)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Corona",
    state: "CA",
  },
  {
    name: "Saugus",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Saugus",
    state: "CA",
  },
  {
    name: "Segerstrom",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Southlake Carroll",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Southlake",
    state: "TX",
  },
  {
    name: "St. Francis (Sacramento)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Sacramento",
    state: "CA",
  },
  {
    name: "Stockdale",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Temecula Valley",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Temecula",
    state: "CA",
  },
  {
    name: "Temescal Canyon",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Lake Elsinore",
    state: "CA",
  },
  {
    name: "The Woodlands",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "The Woodlands",
    state: "TX",
  },
  {
    name: "Torrey Pines",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Trabuco Hills",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Mission Viejo",
    state: "CA",
  },
  {
    name: "Troy",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Fullerton",
    state: "CA",
  },
  {
    name: "Upland",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Upland",
    state: "CA",
  },
  {
    name: "Valencia (Valencia)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Valencia",
    state: "CA",
  },
  {
    name: "Vista Murrieta",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Murrieta",
    state: "CA",
  },
  {
    name: "Warren",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Downey",
    state: "CA",
  },
  {
    name: "Westlake (UT)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Saratoga Springs",
    state: "UT",
  },
  {
    name: "Wilson (Long Beach)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Long Beach",
    state: "CA",
  },
  {
    name: "Woodbridge",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "Agoura",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Agoura Hills",
    state: "CA",
  },
  {
    name: "Air Academy",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Air Force Academy",
    state: "CO",
  },
  {
    name: "ALA - West Foothills",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Waddell",
    state: "AZ",
  },
  {
    name: "Archbishop Riordan",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San Francisco",
    state: "CA",
  },
  {
    name: "Atwater",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Atwater",
    state: "CA",
  },
  {
    name: "Berthoud",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Berthoud",
    state: "CO",
  },
  {
    name: "Bloomington",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Bloomington",
    state: "CA",
  },
  {
    name: "Bonita",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "La Verne",
    state: "CA",
  },
  {
    name: "Boulder",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Boulder",
    state: "CO",
  },
  {
    name: "Brentwood School",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Brophy College Prep",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Burroughs (Ridgecrest)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Ridgecrest",
    state: "CA",
  },
  {
    name: "Campo Verde",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Gilbert",
    state: "AZ",
  },
  {
    name: "Capistrano Valley",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Mission Viejo",
    state: "CA",
  },
  {
    name: "Castaic",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Castaic",
    state: "CA",
  },
  {
    name: "Casteel",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Queen Creek",
    state: "AZ",
  },
  {
    name: "Cathedral Catholic",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Central East",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Chaminade",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "West Hills",
    state: "CA",
  },
  {
    name: "Christian",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "El Cajon",
    state: "CA",
  },
  {
    name: "Claremont",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Claremont",
    state: "CA",
  },
  {
    name: "Clovis West",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Coeur d'Alene",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Coeur d'Alene",
    state: "ID",
  },
  {
    name: "Colony",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Ontario",
    state: "CA",
  },
  {
    name: "Conifer",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Conifer",
    state: "CO",
  },
  {
    name: "Cordova",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Rancho Cordova",
    state: "CA",
  },
  {
    name: "Crater",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Central Point",
    state: "OR",
  },
  {
    name: "Dallas Covenant",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Dallas",
    state: "TX",
  },
  {
    name: "Damonte Ranch",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Reno",
    state: "NV",
  },
  {
    name: "Dana Hills",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Dana Point",
    state: "CA",
  },
  {
    name: "Davis Kaysville",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Kaysville",
    state: "UT",
  },
  {
    name: "Del Campo",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Fair Oaks",
    state: "CA",
  },
  {
    name: "Delano",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Delano",
    state: "CA",
  },
  {
    name: "Desert Hills",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Saint George",
    state: "UT",
  },
  {
    name: "Eagle Rock",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Edison (Huntington Beach)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Huntington Beach",
    state: "CA",
  },
  {
    name: "El Dorado",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Placentia",
    state: "CA",
  },
  {
    name: "El Rancho",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Pico Rivera",
    state: "CA",
  },
  {
    name: "El Toro",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Lake Forest",
    state: "CA",
  },
  {
    name: "Faith Lutheran",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Foothill (Santa Ana)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Foothill Technology (Ventura)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Ventura",
    state: "CA",
  },
  {
    name: "Francis Parker",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Gahr",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Cerritos",
    state: "CA",
  },
  {
    name: "Galena",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Reno",
    state: "NV",
  },
  {
    name: "Georgetown",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Georgetown",
    state: "TX",
  },
  {
    name: "Glendora",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Glendora",
    state: "CA",
  },
  {
    name: "Golden Valley (San Joaquin)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Merced",
    state: "CA",
  },
  {
    name: "Granada",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Livermore",
    state: "CA",
  },
  {
    name: "Hart",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Newhall",
    state: "CA",
  },
  {
    name: "Harvard-Westlake",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Studio City",
    state: "CA",
  },
  {
    name: "Hazel Green",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Hazel Green",
    state: "AL",
  },
  {
    name: "Indio",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Indio",
    state: "CA",
  },
  {
    name: "Jesuit (Sacramento)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Sacramento",
    state: "CA",
  },
  {
    name: "JSerra Catholic",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San Juan Capistrano",
    state: "CA",
  },
  {
    name: "Kennedy (Granada Hills)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Granada Hills",
    state: "CA",
  },
  {
    name: "La Canada",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "La Canada",
    state: "CA",
  },
  {
    name: "La Costa Canyon",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Carlsbad",
    state: "CA",
  },
  {
    name: "La Jolla",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "La Jolla",
    state: "CA",
  },
  {
    name: "Lompoc",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Lompoc",
    state: "CA",
  },
  {
    name: "Los Gatos",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Los Gatos",
    state: "CA",
  },
  {
    name: "Madera South",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Madera",
    state: "CA",
  },
  {
    name: "Marina",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Huntington Beach",
    state: "CA",
  },
  {
    name: "Matilda Torres",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Madera",
    state: "CA",
  },
  {
    name: "Mauldin",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Mauldin",
    state: "SC",
  },
  {
    name: "Mead",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Spokane",
    state: "WA",
  },
  {
    name: "Menlo",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Atherton",
    state: "CA",
  },
  {
    name: "Monache",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Porterville",
    state: "CA",
  },
  {
    name: "Monroe",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "North Hills",
    state: "CA",
  },
  {
    name: "Monrovia",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Monrovia",
    state: "CA",
  },
  {
    name: "Monte Vista (CO)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Monte Vista",
    state: "CO",
  },
  {
    name: "Moorpark",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Moorpark",
    state: "CA",
  },
  {
    name: "Mountain View (Central Coast Sec)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Mountain View",
    state: "CA",
  },
  {
    name: "Mt. Carmel",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Newbury Park",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Newbury Park",
    state: "CA",
  },
  {
    name: "Newport Harbor",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Newport Beach",
    state: "CA",
  },
  {
    name: "Norte Vista",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "North Phoenix Prep",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Northfield",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Denver",
    state: "CO",
  },
  {
    name: "Northridge",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Layton",
    state: "UT",
  },
  {
    name: "Oak Park",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Oak Park",
    state: "CA",
  },
  {
    name: "Pacifica (Garden Grove)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Garden Grove",
    state: "CA",
  },
  {
    name: "Page",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Page",
    state: "AZ",
  },
  {
    name: "Peninsula",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Rolling Hills Estates",
    state: "CA",
  },
  {
    name: "Piedmont Hills",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "San Jose",
    state: "CA",
  },
  {
    name: "Placer",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Auburn",
    state: "CA",
  },
  {
    name: "Pueblo West",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Pueblo West",
    state: "CO",
  },
  {
    name: "Radford (HI)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Honolulu",
    state: "HI",
  },
  {
    name: "Redwood (Larkspur)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Larkspur",
    state: "CA",
  },
  {
    name: "Rosary Academy",
    raceDay: "Friday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Fullerton",
    state: "CA",
  },
  {
    name: "Rio Rico",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Rio Rico",
    state: "AZ",
  },
  {
    name: "Sage Creek",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Carlsbad",
    state: "CA",
  },
  {
    name: "San Franciso University",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San Francisco",
    state: "CA",
  },
  {
    name: "San Gorgonio",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San bernardino",
    state: "CA",
  },
  {
    name: "San Ramon Valley",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Danville",
    state: "CA",
  },
  {
    name: "Santa Margarita",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Rancho Santa Margarita",
    state: "CA",
  },
  {
    name: "Scripps Ranch",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Servite",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Anaheim",
    state: "CA",
  },
  {
    name: "Shiloh Christian",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Springdale",
    state: "AR",
  },
  {
    name: "Silverado",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Victorville",
    state: "CA",
  },
  {
    name: "Somerset Sky Pointe",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Sonora (Sonora)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Sonora",
    state: "CA",
  },
  {
    name: "South Pasadena",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "South Pasadena",
    state: "CA",
  },
  {
    name: "Spanish Springs",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Sparks",
    state: "NV",
  },
  {
    name: "St. Augustine (San Diego)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Taft",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Woodland Hills",
    state: "CA",
  },
  {
    name: "Tahoe-Truckee",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Truckee",
    state: "CA",
  },
  {
    name: "Tesoro",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Las Flores",
    state: "CA",
  },
  {
    name: "The King's Academy (Sunnyvale)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Sunnyvale",
    state: "CA",
  },
  {
    name: "Timnath",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "TImnath",
    state: "CO",
  },
  {
    name: "Tri-Valley",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Grahamsville",
    state: "NY",
  },
  {
    name: "Tulare Western",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Tulare",
    state: "CA",
  },
  {
    name: "University City (San Diego)",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Urbana",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Ijamsville",
    state: "MD",
  },
  {
    name: "Vacaville",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Vacaville",
    state: "CA",
  },
  {
    name: "Venice",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Ventura",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Ventura",
    state: "CA",
  },
  {
    name: "Villa Park",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Villa Park",
    state: "CA",
  },
  {
    name: "Vintage",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Napa",
    state: "CA",
  },
  {
    name: "Walnut",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Walnut",
    state: "CA",
  },
  {
    name: "West Linn",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "West Linn",
    state: "OR",
  },
  {
    name: "West Ranch",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Stevenson Ranch",
    state: "CA",
  },
  {
    name: "Westlake",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Westlake Village",
    state: "CA",
  },
  {
    name: "Westview",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Whitesburg Christian Academy",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Huntsville",
    state: "AL",
  },
  {
    name: "Yorba Linda",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Yorba Linda",
    state: "CA",
  },
  {
    name: "Denton Guyer",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Denton",
    state: "TX",
  },
  {
    name: "Heritage (Brentwood)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Brentwood",
    state: "CA",
  },
  {
    name: "Highland (UT)",
    raceDay: "Saturday Night",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Salt Lake City",
    state: "UT",
  },
  {
    name: "St. Helena",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "St Helena",
    state: "CA",
  },
  {
    name: "Williams Field",
    raceDay: "Saturday Night",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Gilbert",
    state: "AZ",
  },
  {
    name: "Argonaut",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Jackson",
    state: "CA",
  },
  {
    name: "Armijo",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Fairfield",
    state: "CA",
  },
  {
    name: "Arrowhead Christian Academy",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Redlands",
    state: "CA",
  },
  {
    name: "Arvin",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Arvin",
    state: "CA",
  },
  {
    name: "Buhach Colony",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Atwater",
    state: "CA",
  },
  {
    name: "Cabrillo",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Lompoc",
    state: "CA",
  },
  {
    name: "Caldera",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Bend",
    state: "OR",
  },
  {
    name: "Cardinal Newman",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Santa Rosa",
    state: "CA",
  },
  {
    name: "Casa Roble",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Orangevale",
    state: "CA",
  },
  {
    name: "Cathedral City",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Cathedral City",
    state: "CA",
  },
  {
    name: "Charter Oak",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Covina",
    state: "CA",
  },
  {
    name: "Compton",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Compton",
    state: "CA",
  },
  {
    name: "Corona",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Corona",
    state: "CA",
  },
  {
    name: "Cosumnes Oaks",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Elk Grove",
    state: "CA",
  },
  {
    name: "Davis",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Kaysville",
    state: "UT",
  },
  {
    name: "El Camino Real",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Woodland Hills",
    state: "CA",
  },
  {
    name: "El Cerrito",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "El Cerrito",
    state: "CA",
  },
  {
    name: "Freedom (Tampa)",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Tampa",
    state: "FL",
  },
  {
    name: "Frontier",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Gilbert Christian",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Gilbert",
    state: "AZ",
  },
  {
    name: "Henry M. Gunn",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Palo Alto",
    state: "CA",
  },
  {
    name: "Immanuel",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Reedley",
    state: "CA",
  },
  {
    name: "Indian Springs",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "San Bernardino",
    state: "CA",
  },
  {
    name: "John Marshall",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Jurupa Hills",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Fontana",
    state: "CA",
  },
  {
    name: "Justin Garza",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Lakewood (CA)",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Lakewood",
    state: "CA",
  },
  {
    name: "Leuzinger",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Lawndale",
    state: "CA",
  },
  {
    name: "Lincoln (Stockton)",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Stockton",
    state: "CA",
  },
  {
    name: "Los Osos",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Rancho Cucamonga",
    state: "CA",
  },
  {
    name: "Lowry",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Winnemucca",
    state: "NV",
  },
  {
    name: "Madera",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Madera",
    state: "CA",
  },
  {
    name: "Marin Catholic",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Kentfield",
    state: "CA",
  },
  {
    name: "Marlborough",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Monte Vista Christian",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Watsonville",
    state: "CA",
  },
  {
    name: "Murrieta Mesa",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Murrieta",
    state: "CA",
  },
  {
    name: "Nipomo",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Nipomo",
    state: "CA",
  },
  {
    name: "Norco",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Norco",
    state: "CA",
  },
  {
    name: "North Hollywood",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "North Hollywood",
    state: "CA",
  },
  {
    name: "Oakwood",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "North Hollywood",
    state: "CA",
  },
  {
    name: "Ogden",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Ogden",
    state: "UT",
  },
  {
    name: "Orange Lutheran",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Orange",
    state: "CA",
  },
  {
    name: "Palm Desert",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Palm Desert",
    state: "CA",
  },
  {
    name: "Palmdale Academy Charter",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Palmdale",
    state: "CA",
  },
  {
    name: "Palo Verde",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Park City",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Park CIty",
    state: "UT",
  },
  {
    name: "Pinecrest Academy Cadence",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Henderson",
    state: "NV",
  },
  {
    name: "Pitman",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Turlock",
    state: "CA",
  },
  {
    name: "Quartz Hill",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Quartz Hill",
    state: "CA",
  },
  {
    name: "Rancho Mirage",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Rancho Mirage",
    state: "CA",
  },
  {
    name: "Regis Jesuit",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Aurora",
    state: "CO",
  },
  {
    name: "Robert F Kennedy Community Schools",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "San Dimas",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "San Dimas",
    state: "CA",
  },
  {
    name: "San Pasqual",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Escondido",
    state: "CA",
  },
  {
    name: "Sandra Day O'Connor",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Santa Teresa",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "San Jose",
    state: "CA",
  },
  {
    name: "Santa Ynez",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Solvang",
    state: "CA",
  },
  {
    name: "Saratoga",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Saratoga",
    state: "CA",
  },
  {
    name: "Southeast Career Technical Academy",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Seton Catholic",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Chandler",
    state: "AZ",
  },
  {
    name: "Shadow Ridge",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Simi Valley",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Simi Valley",
    state: "CA",
  },
  {
    name: "Skyline",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Oakland",
    state: "CA",
  },
  {
    name: "Springville",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Springville",
    state: "UT",
  },
  {
    name: "Tooele",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Tooele",
    state: "UT",
  },
  {
    name: "Tracy",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Tracy",
    state: "CA",
  },
  {
    name: "Vacaville Christian",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Vacaville",
    state: "CA",
  },
  {
    name: "Valley Christian",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Cerritos",
    state: "CA",
  },
  {
    name: "Western Christian",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Upland",
    state: "CA",
  },
  {
    name: "Westmont",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.a,
    city: "Campbell",
    state: "CA",
  },
  {
    name: "Yucaipa",
    raceDay: "Saturday Morning",
    division: divisions.five,
    varsityHeat: heats.b,
    city: "Yucaipa",
    state: "CA",
  },
]
  .map((team, index) => ({
    ...team,
    id: index,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));
