import { ParticipatingTeamType } from "@/types";
import { divisions, heats } from "./races";

export const participatingTeams: ParticipatingTeamType[] = [
  {
    name: "Academy for Academic Excellence",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Apple Valley",
    state: "CA",
  },
  {
    name: "Academy of Careers and Exploration",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Helendale",
    state: "CA",
  },
  {
    name: "Agoura",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Agoura Hills",
    state: "CA",
  },
  {
    name: "Air Academy",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Colorado Springs",
    state: "CO",
  },
  {
    name: "ALA - Gilbert North",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Gilbert",
    state: "AZ",
  },
  {
    name: "ALA - Queen Creek",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Queen Creek",
    state: "AZ",
  },
  {
    name: "ALA - West Foothills",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Waddell",
    state: "AZ",
  },
  {
    name: "Alamosa",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Alamosa",
    state: "CO",
  },
  {
    name: "Alisal",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Salinas",
    state: "CA",
  },
  {
    name: "Aliso Niguel",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Aliso Viejo",
    state: "CA",
  },
  {
    name: "Alta Loma",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Alta Loma",
    state: "CA",
  },
  {
    name: "Anaheim",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Anaheim",
    state: "CA",
  },
  {
    name: "Anthem Prep",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Apple Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Apple Valley",
    state: "CA",
  },
  {
    name: "Arbor View",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "las vegas",
    state: "NV",
  },
  {
    name: "Arcadia",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Arcadia",
    state: "CA",
  },
  {
    name: "Arizona College Preparatory",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Chandler",
    state: "AZ",
  },
  {
    name: "Arlington",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Armijo",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Fairfield",
    state: "CA",
  },
  {
    name: "Arroyo (SS)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "El Monte",
    state: "CA",
  },
  {
    name: "Arroyo Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "San Bernardino",
    state: "CA",
  },
  {
    name: "Astoria",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Astoria",
    state: "OR",
  },
  {
    name: "Atascadero",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Atascadero",
    state: "CA",
  },
  {
    name: "Atwater",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Atwater",
    state: "CA",
  },
  {
    name: "Austin Vandegrift",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Austin",
    state: "TX",
  },
  {
    name: "Ayala",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Chino Hills",
    state: "CA",
  },
  {
    name: "Bakersfield",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Banning",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Banning",
    state: "CA",
  },
  {
    name: "Basalt",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Basalt",
    state: "CO",
  },
  {
    name: "Basha",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Chandler",
    state: "AZ",
  },
  {
    name: "Basic",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Henderson",
    state: "NV",
  },
  {
    name: "Beaumont",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Beaumont",
    state: "CA",
  },
  {
    name: "Beckman",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "Bellflower",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Bellflower",
    state: "CA",
  },
  {
    name: "Belmont",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Berkeley",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Berkeley",
    state: "CA",
  },
  {
    name: "Big Bear",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Big Bear City",
    state: "CA",
  },
  {
    name: "Birmingham",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Lake Balboa",
    state: "CA",
  },
  {
    name: "Bishop Amat",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "La Puente",
    state: "CA",
  },
  {
    name: "Bishop Montgomery",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Torrance",
    state: "CA",
  },
  {
    name: "Bloomington",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Bloomington",
    state: "CA",
  },
  {
    name: "Bolsa Grande",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Garden Grove",
    state: "CA",
  },
  {
    name: "Bonita",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "La Verne",
    state: "CA",
  },
  {
    name: "Boulder",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Boulder",
    state: "CO",
  },
  {
    name: "Brentwood",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Bridgeland",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Cypress",
    state: "TX",
  },
  {
    name: "Brophy College Prep",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Buchanan",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Clovis",
    state: "CA",
  },
  {
    name: "Buena",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Ventura",
    state: "CA",
  },
  {
    name: "Buena Park",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Buena Park",
    state: "CA",
  },
  {
    name: "Bullard",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Burroughs (Ridgecrest)",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Ridgecrest",
    state: "CA",
  },
  {
    name: "Cajon",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Bernardino",
    state: "CA",
  },
  {
    name: "Cal. Acad. Math/Science",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Carson",
    state: "CA",
  },
  {
    name: "Calabasas",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Calabasas",
    state: "CA",
  },
  {
    name: "Caldera",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Bend",
    state: "OR",
  },
  {
    name: "California (Whittier)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Whittier",
    state: "CA",
  },
  {
    name: "Calvary Chapel (Downey)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Downey",
    state: "CA",
  },
  {
    name: "Calvary Chapel (Santa Ana)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Camarillo",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Camarillo",
    state: "CA",
  },
  {
    name: "Campo Verde",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Gilbert",
    state: "AZ",
  },
  {
    name: "Cantwell-Sacred Heart",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Montebello",
    state: "CA",
  },
  {
    name: "Canyon (Anaheim)",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Anaheim",
    state: "CA",
  },
  {
    name: "Canyon (Canyon Country)",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Canyon Country",
    state: "CA",
  },
  {
    name: "Canyon Crest Academy",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Capistrano Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Mission Viejo",
    state: "CA",
  },
  {
    name: "Cardinal Newman",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Santa Rosa",
    state: "CA",
  },
  {
    name: "Carlmont",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Belmont",
    state: "CA",
  },
  {
    name: "Carlsbad",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Carlsbad",
    state: "CA",
  },
  {
    name: "Carson",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Carson City",
    state: "NV",
  },
  {
    name: "Carter",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Rialto",
    state: "CA",
  },
  {
    name: "Casa Roble",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Orangevale",
    state: "CA",
  },
  {
    name: "Castaic",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Castaic",
    state: "CA",
  },
  {
    name: "Casteel",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Queen Creek",
    state: "AZ",
  },
  {
    name: "Castro Valley",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Castro Valley",
    state: "CA",
  },
  {
    name: "Cathedral",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Cathedral Catholic",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Cathedral City",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Cathedral City",
    state: "CA",
  },
  {
    name: "Centennial",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Centennial (Corona)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Corona",
    state: "CA",
  },
  {
    name: "Centennial (NV)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Central",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Central City Value",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Central East",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Central Valley Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Visalia",
    state: "CA",
  },
  {
    name: "Century",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Cerritos",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Cerritos",
    state: "CA",
  },
  {
    name: "Chadwick",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Palos Verdes Peninsula",
    state: "CA",
  },
  {
    name: "Chandler Preparatory",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Chandler",
    state: "AZ",
  },
  {
    name: "Channel Islands",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Oxnard",
    state: "CA",
  },
  {
    name: "Charter Oak",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Covina",
    state: "CA",
  },
  {
    name: "Cherry Creek",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Greenwood Village",
    state: "CO",
  },
  {
    name: "Cheyenne Mountain",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Colorado Springs",
    state: "CO",
  },
  {
    name: "Chino",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Chino",
    state: "CA",
  },
  {
    name: "Chino Hills",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Chino Hills",
    state: "CA",
  },
  {
    name: "Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "El Cajon",
    state: "CA",
  },
  {
    name: "Christian Brothers",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Sacramento",
    state: "CA",
  },
  {
    name: "Citrus Valley",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Redlands",
    state: "CA",
  },
  {
    name: "Claremont",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Claremont",
    state: "CA",
  },
  {
    name: "Clark",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Classical Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Escondido",
    state: "CA",
  },
  {
    name: "Cleveland",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Reseda",
    state: "CA",
  },
  {
    name: "Clovis",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Clovis",
    state: "CA",
  },
  {
    name: "Clovis East",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Clovis",
    state: "CA",
  },
  {
    name: "Clovis West",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Coachella Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Thermal",
    state: "CA",
  },
  {
    name: "Coconino",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Flagstaff",
    state: "AZ",
  },
  {
    name: "Coeur D'Alene",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Coeur D'Alene",
    state: "ID",
  },
  {
    name: "Colony",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Ontario",
    state: "CA",
  },
  {
    name: "Colton",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Colton",
    state: "CA",
  },
  {
    name: "Convent & Stuart Hall",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "San Francisco",
    state: "CA",
  },
  {
    name: "Cordova",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Rancho Cordova",
    state: "CA",
  },
  {
    name: "Corona",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Corona",
    state: "CA",
  },
  {
    name: "Corona del Mar",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Newport Beach",
    state: "CA",
  },
  {
    name: "Coronado",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Coronado",
    state: "CA",
  },
  {
    name: "Costa Mesa",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Costa Mesa",
    state: "CA",
  },
  {
    name: "Covina",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Covina",
    state: "CA",
  },
  {
    name: "Crater",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Central Point",
    state: "OR",
  },
  {
    name: "Crawford",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Crean Lutheran",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "Crescenta Valley",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "La Crescenta",
    state: "CA",
  },
  {
    name: "Crismon",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Queen Creek",
    state: "AZ",
  },
  {
    name: "Cypress",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Cypress",
    state: "CA",
  },
  {
    name: "Dallas Covenant",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Dallas",
    state: "TX",
  },
  {
    name: "Damien",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "La Verne",
    state: "CA",
  },
  {
    name: "Damonte Ranch",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Reno",
    state: "NV",
  },
  {
    name: "Dana Hills",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Dana Point",
    state: "CA",
  },
  {
    name: "Deer Valley",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Glendale",
    state: "AZ",
  },
  {
    name: "Del Campo",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Fair Oaks",
    state: "CA",
  },
  {
    name: "Del Lago Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Escondido",
    state: "CA",
  },
  {
    name: "Del Norte",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Del Oro",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Del Sol",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Oxnard",
    state: "CA",
  },
  {
    name: "Delano",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Delano",
    state: "CA",
  },
  {
    name: "Denton Braswell",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Aubrey",
    state: "TX",
  },
  {
    name: "Desert Christian (Lancaster)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Lancaster",
    state: "CA",
  },
  {
    name: "Desert Hills",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "St. George",
    state: "UT",
  },
  {
    name: "Desert Vista",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Diamond Bar",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Diamond Bar",
    state: "CA",
  },
  {
    name: "Dinuba",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Dinuba",
    state: "CA",
  },
  {
    name: "Don Bosco Tech",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Rosemead",
    state: "CA",
  },
  {
    name: "Don Lugo",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Chino",
    state: "CA",
  },
  {
    name: "Dos Pueblos",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Goleta",
    state: "CA",
  },
  {
    name: "Dougherty Valley",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Ramon",
    state: "CA",
  },
  {
    name: "Downey (SJ)",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Modesto",
    state: "CA",
  },
  {
    name: "Downey (SS)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Downey",
    state: "CA",
  },
  {
    name: "Eagle",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Eagle",
    state: "ID",
  },
  {
    name: "Eagle Rock",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Eastlake",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Chula Vista",
    state: "CA",
  },
  {
    name: "Eastside (9)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Lancaster",
    state: "CA",
  },
  {
    name: "Edison (HB)",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Huntington Beach",
    state: "CA",
  },
  {
    name: "El Camino (Oceanside)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Oceanside",
    state: "CA",
  },
  {
    name: "El Diamante",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Visalia",
    state: "CA",
  },
  {
    name: "El Dorado",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Placentia",
    state: "CA",
  },
  {
    name: "El Modena",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Orange",
    state: "CA",
  },
  {
    name: "El Rancho",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Pico Rivera",
    state: "CA",
  },
  {
    name: "El Toro",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Lake Forest",
    state: "CA",
  },
  {
    name: "Eleanor Roosevelt",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Eastvale",
    state: "CA",
  },
  {
    name: "Elsinore",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Wildomar",
    state: "CA",
  },
  {
    name: "Entrepreneur (Fontana)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Fontana",
    state: "CA",
  },
  {
    name: "Entrepreneur (Highland)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Highland",
    state: "CA",
  },
  {
    name: "Enumclaw",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Enumclaw",
    state: "WA",
  },
  {
    name: "Escondido",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Escondido",
    state: "CA",
  },
  {
    name: "Esperanza",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Anaheim",
    state: "CA",
  },
  {
    name: "Etiwanda",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Rancho Cucamonga",
    state: "CA",
  },
  {
    name: "Faith Lutheran",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Federal Way",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Federal Way",
    state: "WA",
  },
  {
    name: "Flintridge Prep",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "La Cañada",
    state: "CA",
  },
  {
    name: "Fontana",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Fontana",
    state: "CA",
  },
  {
    name: "Foothill",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Henderson",
    state: "NV",
  },
  {
    name: "Foothill (Santa Ana)",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Foothill Technology",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Ventura",
    state: "CA",
  },
  {
    name: "Fossil Ridge",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Fort Collins",
    state: "CO",
  },
  {
    name: "Fountain Valley",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Fountain Valley",
    state: "CA",
  },
  {
    name: "Fresno Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Frontier",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Fullerton",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Fullerton",
    state: "CA",
  },
  {
    name: "Gabrielino",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Gabriel",
    state: "CA",
  },
  {
    name: "Gahr",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Cerritos",
    state: "CA",
  },
  {
    name: "Garfield",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Georgetown",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Georgetown",
    state: "TX",
  },
  {
    name: "Glen A. Wilson (Hacienda Heights)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Hacienda Heights",
    state: "CA",
  },
  {
    name: "Glendale",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Glendale",
    state: "CA",
  },
  {
    name: "Glendale Preparatory Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Peoria",
    state: "AZ",
  },
  {
    name: "Glendora",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Glendora",
    state: "CA",
  },
  {
    name: "Godinez",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Golden Valley (SJ)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Merced",
    state: "CA",
  },
  {
    name: "Golden Valley (SS)",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Santa clarita",
    state: "CA",
  },
  {
    name: "Granada Hills",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Granada Hills",
    state: "CA",
  },
  {
    name: "Grand Terrace",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Grand Terrace",
    state: "CA",
  },
  {
    name: "Granite Hills (Apple Valley)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Apple Valley",
    state: "CA",
  },
  {
    name: "Great Oak",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Temecula",
    state: "CA",
  },
  {
    name: "Green Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Henderson",
    state: "NV",
  },
  {
    name: "Grossmont",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "El Cajon",
    state: "CA",
  },
  {
    name: "Hamilton (AZ)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Chandler",
    state: "AZ",
  },
  {
    name: "Hamilton (CA)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Harrison",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Kennesaw",
    state: "GA",
  },
  {
    name: "Hart",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Santa Clarita",
    state: "CA",
  },
  {
    name: "Harvard-Westlake",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Studio City",
    state: "CA",
  },
  {
    name: "Hawaii Baptist Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Honolulu",
    state: "HI",
  },
  {
    name: "Hawthorne Math & Science Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Hawthorne",
    state: "CA",
  },
  {
    name: "Helix",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "La Mesa",
    state: "CA",
  },
  {
    name: "Hemet",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Hemet",
    state: "CA",
  },
  {
    name: "Herriman",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Herriman",
    state: "UT",
  },
  {
    name: "Hesperia",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Hesperia",
    state: "CA",
  },
  {
    name: "Highland",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Highland (SS)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Palmdale",
    state: "CA",
  },
  {
    name: "Highland Baptist Christian",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "New Iberia",
    state: "LA",
  },
  {
    name: "Hill City",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Hill City",
    state: "SD",
  },
  {
    name: "Hillcrest",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Hilmar",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "hilmar",
    state: "CA",
  },
  {
    name: "Holliday",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Holliday",
    state: "TX",
  },
  {
    name: "Homestead",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Cupertino",
    state: "CA",
  },
  {
    name: "Hoover",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Glendale",
    state: "CA",
  },
  {
    name: "Hopi",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Keams Canyon",
    state: "AZ",
  },
  {
    name: "Huntington Beach",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Huntington Beach",
    state: "CA",
  },
  {
    name: "Immanuel",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Reedley",
    state: "CA",
  },
  {
    name: "Independence",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Indio",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Indio",
    state: "CA",
  },
  {
    name: "International School of Los Angeles",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Burbank",
    state: "CA",
  },
  {
    name: "Irvine",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "J Serra Catholic",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "San Juan Capistrano",
    state: "CA",
  },
  {
    name: "Jesuit",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Carmichael",
    state: "CA",
  },
  {
    name: "John W. North",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Justin Garza",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Kaiser",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Fontana",
    state: "CA",
  },
  {
    name: "Katella",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Anaheim",
    state: "CA",
  },
  {
    name: "Kennedy",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Granada Hills",
    state: "CA",
  },
  {
    name: "Kennedy (La Palma)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "La Palma",
    state: "CA",
  },
  {
    name: "Kerman",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Kerman",
    state: "CA",
  },
  {
    name: "Kimball",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Tracy",
    state: "CA",
  },
  {
    name: "La Canada",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "La Cañada",
    state: "CA",
  },
  {
    name: "La Costa Canyon",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Carlsbad",
    state: "CA",
  },
  {
    name: "La Habra",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "La Habra",
    state: "CA",
  },
  {
    name: "La Jolla",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "La Jolla",
    state: "CA",
  },
  {
    name: "La Jolla Country Day",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "La Jolla",
    state: "CA",
  },
  {
    name: "La Mirada",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "La Mirada",
    state: "CA",
  },
  {
    name: "La Quinta (La Quinta)",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "La Quinta",
    state: "CA",
  },
  {
    name: "La Quinta (Westminster)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Westminster",
    state: "CA",
  },
  {
    name: "La Salle",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Pasadena",
    state: "CA",
  },
  {
    name: "La Serna",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Whittier",
    state: "CA",
  },
  {
    name: "La Sierra",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Laguna Beach",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Laguna Beach",
    state: "CA",
  },
  {
    name: "Laguna Hills",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Laguna Hills",
    state: "CA",
  },
  {
    name: "Lakewood (WA)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Arlington",
    state: "WA",
  },
  {
    name: "Lakewood (CA)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Lakewood",
    state: "CA",
  },
  {
    name: "Lancaster",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Lancaster",
    state: "CA",
  },
  {
    name: "Liberty",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Henderson",
    state: "NV",
  },
  {
    name: "Liberty - Winchester",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Winchester",
    state: "CA",
  },
  {
    name: "Linfield Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Temecula",
    state: "CA",
  },
  {
    name: "Littlerock",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Littlerock",
    state: "CA",
  },
  {
    name: "Lompoc",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Lompoc",
    state: "CA",
  },
  {
    name: "Los Altos",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Hacienda Heights",
    state: "CA",
  },
  {
    name: "Los Gatos",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Los Gatos",
    state: "CA",
  },
  {
    name: "Los Osos",
    raceDay: "Friday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Rancho Cucamonga",
    state: "CA",
  },
  {
    name: "Loyola",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Lucerne Valley",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Lucerne Valley",
    state: "CA",
  },
  {
    name: "Madera",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Madera",
    state: "CA",
  },
  {
    name: "Madera South",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Madera",
    state: "CA",
  },
  {
    name: "Madison",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Maranatha",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Pasadena",
    state: "CA",
  },
  {
    name: "maranatha christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "SANDIEGO , CA",
    state: "CA",
  },
  {
    name: "Maria Carrillo",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Santa Rosa",
    state: "CA",
  },
  {
    name: "Marina",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Huntington Beach",
    state: "CA",
  },
  {
    name: "Martin Luther King",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Mary Star of the Sea",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "San Pedro",
    state: "CA",
  },
  {
    name: "Mater Dei",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Matilda Torres",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Madera",
    state: "CA",
  },
  {
    name: "Mayfair",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Lakewood",
    state: "CA",
  },
  {
    name: "McClatchy",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Sacramento",
    state: "CA",
  },
  {
    name: "McFarland",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "McFarland",
    state: "CA",
  },
  {
    name: "Menlo",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Atherton",
    state: "CA",
  },
  {
    name: "Menlo-Atherton",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Atherton",
    state: "CA",
  },
  {
    name: "Merced",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Merced",
    state: "CA",
  },
  {
    name: "Mica Mountain",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Tucson",
    state: "AZ",
  },
  {
    name: "Middle College",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Millikan",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Long Beach",
    state: "CA",
  },
  {
    name: "Mira Costa",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Manhattan Beach",
    state: "CA",
  },
  {
    name: "Mission Hills",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Marcos",
    state: "CA",
  },
  {
    name: "Mission Viejo",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Mission Viejo",
    state: "CA",
  },
  {
    name: "Mission Vista",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Oceanside",
    state: "CA",
  },
  {
    name: "Moapa Valley",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Overton",
    state: "NV",
  },
  {
    name: "Monache",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Porterville",
    state: "CA",
  },
  {
    name: "Monroe",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "North Hills",
    state: "CA",
  },
  {
    name: "Monrovia",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Monrovia",
    state: "CA",
  },
  {
    name: "Monte Vista (CA)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Danville",
    state: "CA",
  },
  {
    name: "Monte Vista (CO)",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Monte Vista",
    state: "CO",
  },
  {
    name: "Moorpark",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Moorpark",
    state: "CA",
  },
  {
    name: "Moses Lake",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Moses Lake",
    state: "WA",
  },
  {
    name: "Mountain Ridge",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Glendale",
    state: "AZ",
  },
  {
    name: "Mountain View (Mt View)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Mountain View",
    state: "CA",
  },
  {
    name: "Mountain View (El Monte)",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "El Monte",
    state: "CA",
  },
  {
    name: "Mt Carmel",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Murrieta Valley",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Murrieta",
    state: "CA",
  },
  {
    name: "Newbury Park",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Newbury Park",
    state: "CA",
  },
  {
    name: "Nogales",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "La Puente",
    state: "CA",
  },
  {
    name: "Norco",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Norco",
    state: "CA",
  },
  {
    name: "Norte Vista",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "North Bakersfield",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "North Eugene",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Eugene",
    state: "OR",
  },
  {
    name: "North Hollywood",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "North Hollywood",
    state: "CA",
  },
  {
    name: "North Phoenix Prep",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "North Torrance",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Torrance",
    state: "CA",
  },
  {
    name: "Northview",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Covina",
    state: "CA",
  },
  {
    name: "Northwest Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Northwood",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "Norwalk",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Norwalk",
    state: "CA",
  },
  {
    name: "Notre Dame (Sherman Oaks)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Sherman Oaks",
    state: "CA",
  },
  {
    name: "NOVA Academy Early College",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Nueva",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "San Mateo",
    state: "CA",
  },
  {
    name: "Oak Hills",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Oak Hills",
    state: "CA",
  },
  {
    name: "Oak Park",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Oak Park",
    state: "CA",
  },
  {
    name: "Oak Ridge",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "El Dorado Hills",
    state: "CA",
  },
  {
    name: "Oaks Christian",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Westlake Village",
    state: "CA",
  },
  {
    name: "Ocean View",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Huntington Beach",
    state: "CA",
  },
  {
    name: "Ogden",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Ogden",
    state: "UT",
  },
  {
    name: "Olympian",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Chula Vista",
    state: "CA",
  },
  {
    name: "Olympus",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Holladay",
    state: "UT",
  },
  {
    name: "Ontario",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Ontario",
    state: "CA",
  },
  {
    name: "Ontario Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Ontario",
    state: "CA",
  },
  {
    name: "Orange",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Orange",
    state: "CA",
  },
  {
    name: "Orange County School of the Arts",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Orange Lutheran",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Orange",
    state: "CA",
  },
  {
    name: "Orange Vista",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Perris",
    state: "CA",
  },
  {
    name: "Orem",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Orem",
    state: "UT",
  },
  {
    name: "Our Lady of Peace",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Oxford Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Cypress",
    state: "CA",
  },
  {
    name: "Oxnard",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Oxnard",
    state: "CA",
  },
  {
    name: "Pacific",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Bernardino",
    state: "CA",
  },
  {
    name: "Pacifica (Garden Grove)",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Garden Grove",
    state: "CA",
  },
  {
    name: "Pacifica Christian OC",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Newport Beach",
    state: "CA",
  },
  {
    name: "Page",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Page",
    state: "AZ",
  },
  {
    name: "Palisades Charter",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Pacific Palisades",
    state: "CA",
  },
  {
    name: "Palm Desert",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Palm Desert",
    state: "CA",
  },
  {
    name: "Paloma Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Menifee",
    state: "CA",
  },
  {
    name: "Palos Verdes",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Palos Verdes Estates",
    state: "CA",
  },
  {
    name: "Paramount",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Paramount",
    state: "CA",
  },
  {
    name: "Pasadena",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Pasadena",
    state: "CA",
  },
  {
    name: "Patrick Henry",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Patriot",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Jurupa Valley",
    state: "CA",
  },
  {
    name: "Peninsula",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Rolling Hills Estates",
    state: "CA",
  },
  {
    name: "Perry",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Gilbert",
    state: "AZ",
  },
  {
    name: "Pinnacle",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Pioneer Valley",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Santa Maria",
    state: "CA",
  },
  {
    name: "Placer",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Auburn",
    state: "CA",
  },
  {
    name: "Point Loma",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Poly (Long Beach)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Long Beach",
    state: "CA",
  },
  {
    name: "Poly (Riverside)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Pomona Catholic",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Pomona",
    state: "CA",
  },
  {
    name: "Ponderosa",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Shingle Springs",
    state: "CA",
  },
  {
    name: "Portola (Irvine)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "Poway",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Poway",
    state: "CA",
  },
  {
    name: "Quartz Hill",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Lancaster",
    state: "CA",
  },
  {
    name: "Queen Creek",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Queen Creek",
    state: "AZ",
  },
  {
    name: "Ramona (Riverside)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Rancho Alamitos",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Garden Grove",
    state: "CA",
  },
  {
    name: "Rancho Bernardo",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Rancho Buena Vista",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Vista",
    state: "CA",
  },
  {
    name: "Rancho Cucamonga",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Rancho Cucamonga",
    state: "CA",
  },
  {
    name: "Rancho Verde",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Moreno Valley",
    state: "CA",
  },
  {
    name: "Redlands",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Redlands",
    state: "CA",
  },
  {
    name: "Redlands East Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Redlands",
    state: "CA",
  },
  {
    name: "Redondo Union",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Redondo Beach",
    state: "CA",
  },
  {
    name: "Redwood (Larkspur)",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Larkspur",
    state: "CA",
  },
  {
    name: "Righetti",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Santa Maria",
    state: "CA",
  },
  {
    name: "Rim of the World",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Lake Arrowhead",
    state: "CA",
  },
  {
    name: "Rio Americano",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Sacramento",
    state: "CA",
  },
  {
    name: "Rio Mesa",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Oxnard",
    state: "CA",
  },
  {
    name: "Rio Rico",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Rio Rico",
    state: "AZ",
  },
  {
    name: "Riverbank",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Riverbank",
    state: "CA",
  },
  {
    name: "Riverdale Ridge",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Thornton",
    state: "CO",
  },
  {
    name: "Rock Canyon",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Highlands Ranch",
    state: "CO",
  },
  {
    name: "Roosevelt",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "Rosary",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Fullerton",
    state: "CA",
  },
  {
    name: "Rowland",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Rowland Heights",
    state: "CA",
  },
  {
    name: "Royal",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Simi Valley",
    state: "CA",
  },
  {
    name: "Sabino",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Tucson",
    state: "AZ",
  },
  {
    name: "Sage Creek",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Carlsbad",
    state: "CA",
  },
  {
    name: "Sage Hill",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Newport Coast",
    state: "CA",
  },
  {
    name: "Salesian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Samueli Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "San Bernardino",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Bernardino",
    state: "CA",
  },
  {
    name: "San Clemente",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Clemente",
    state: "CA",
  },
  {
    name: "San Diego",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "San Gorgonio",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San Bernardino",
    state: "CA",
  },
  {
    name: "San Jacinto",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "San Jacinto",
    state: "CA",
  },
  {
    name: "San Joaquin Memorial",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Fresno",
    state: "CA",
  },
  {
    name: "San Juan Hills",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Juan Capistrano",
    state: "CA",
  },
  {
    name: "San Marin",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Novato",
    state: "CA",
  },
  {
    name: "San Marino",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Marino",
    state: "CA",
  },
  {
    name: "San Pedro",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "San Pedro",
    state: "CA",
  },
  {
    name: "San Ramon Valley",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Danville",
    state: "CA",
  },
  {
    name: "Sanger",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Sanger",
    state: "CA",
  },
  {
    name: "Santa Ana",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Santa Ana Valley",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Santa Clara",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Oxnard",
    state: "CA",
  },
  {
    name: "Santa Fe",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Santa Fe Springs",
    state: "CA",
  },
  {
    name: "Santa Fe Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Solana Beach",
    state: "CA",
  },
  {
    name: "Santa Fe Prep",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Santa Fe",
    state: "NM",
  },
  {
    name: "Santa Margarita",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Rancho Santa Margarita",
    state: "CA",
  },
  {
    name: "Santa Monica",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Santa Monica",
    state: "CA",
  },
  {
    name: "Santa Paula",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Santa Paula",
    state: "CA",
  },
  {
    name: "Santa Rosa Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Menifee",
    state: "CA",
  },
  {
    name: "Santa Ynez",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Solvang",
    state: "CA",
  },
  {
    name: "Santana",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Santee",
    state: "CA",
  },
  {
    name: "Santee EC",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Santiago (Corona)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Corona",
    state: "CA",
  },
  {
    name: "Santiago (Garden Grove)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Garden Grove",
    state: "CA",
  },
  {
    name: "Saugus",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Saugus",
    state: "CA",
  },
  {
    name: "Savanna",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Anaheim",
    state: "CA",
  },
  {
    name: "Schurr",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Montebello",
    state: "CA",
  },
  {
    name: "Scripps Ranch",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Segerstrom",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Santa Ana",
    state: "CA",
  },
  {
    name: "Serrano",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Phelan",
    state: "CA",
  },
  {
    name: "Servite",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Anaheim",
    state: "CA",
  },
  {
    name: "Seton Catholic",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Chandler",
    state: "AZ",
  },
  {
    name: "Shadow Hills",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Indio",
    state: "CA",
  },
  {
    name: "Shadow Mountain",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Shadow Ridge (NV)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Silverado",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Victorville",
    state: "CA",
  },
  {
    name: "Simi Valley",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Simi Valley",
    state: "CA",
  },
  {
    name: "Somerset Academy Sky Pointe",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Las Vegas",
    state: "NV",
  },
  {
    name: "Sonora",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Sonora",
    state: "CA",
  },
  {
    name: "Sonora (La Habra)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "La Habra",
    state: "CA",
  },
  {
    name: "South Hills",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "West Covina",
    state: "CA",
  },
  {
    name: "South Pasadena",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "South Pasadena",
    state: "CA",
  },
  {
    name: "South Torrance",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Torrance",
    state: "CA",
  },
  {
    name: "St Augustine",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "St Francis",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Sacramento",
    state: "CA",
  },
  {
    name: "St Helena",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "St Helena",
    state: "CA",
  },
  {
    name: "St Mary's College",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Berkeley",
    state: "CA",
  },
  {
    name: "St. Francis (La Canada)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "La Cañada Flintridge",
    state: "CA",
  },
  {
    name: "St. Joseph (Lakewood)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Lakewood",
    state: "CA",
  },
  {
    name: "St. Lucy's",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Glendora",
    state: "CA",
  },
  {
    name: "St. Margaret's",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "San Juan Capistrano",
    state: "CA",
  },
  {
    name: "St. Monica",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Santa Monica",
    state: "CA",
  },
  {
    name: "St. Monica Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Montrose",
    state: "CA",
  },
  {
    name: "St. Paul",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Santa Fe Springs",
    state: "CA",
  },
  {
    name: "Stockdale",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Bakersfield",
    state: "CA",
  },
  {
    name: "Summerville",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Tuolumne",
    state: "CA",
  },
  {
    name: "Sun Valley Magnet",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Sun Valley",
    state: "CA",
  },
  {
    name: "Sunny Hills",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Fullerton",
    state: "CA",
  },
  {
    name: "Taft (William Howard)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Woodland Hills",
    state: "CA",
  },
  {
    name: "Tahoe-Truckee",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Truckee",
    state: "CA",
  },
  {
    name: "Temecula Prep",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Winchester",
    state: "CA",
  },
  {
    name: "Temecula Valley",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Temecula",
    state: "CA",
  },
  {
    name: "Temple City",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Temple City",
    state: "CA",
  },
  {
    name: "Terra Linda",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "San Rafael",
    state: "CA",
  },
  {
    name: "Tesoro",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Las Flores",
    state: "CA",
  },
  {
    name: "The Bishop's School",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "La Jolla",
    state: "CA",
  },
  {
    name: "Thousand Oaks",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Thousand Oaks",
    state: "CA",
  },
  {
    name: "ThunderRidge",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Highlands Ranch",
    state: "CO",
  },
  {
    name: "Thurston",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Springfield",
    state: "OR",
  },
  {
    name: "Timnath",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Timnath",
    state: "CO",
  },
  {
    name: "Timpview",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Provo",
    state: "VT",
  },
  {
    name: "Torrance",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Torrance",
    state: "CA",
  },
  {
    name: "Torrey Pines",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Trabuco Hills",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Mission Viejo",
    state: "CA",
  },
  {
    name: "Trinity Classical Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Valencia",
    state: "CA",
  },
  {
    name: "Triumph Charter",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Sylmar",
    state: "CA",
  },
  {
    name: "Troy",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Fullerton",
    state: "CA",
  },
  {
    name: "Tulare Union",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Tulare",
    state: "CA",
  },
  {
    name: "Tulare Western",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Tulare",
    state: "CA",
  },
  {
    name: "Turlock",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Turlock",
    state: "CA",
  },
  {
    name: "Tustin",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Tustin",
    state: "CA",
  },
  {
    name: "Union Catholic Reg",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Scotch Plains",
    state: "NJ",
  },
  {
    name: "Union Mine",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "El Dorado",
    state: "CA",
  },
  {
    name: "United Christian Academy",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Ranch Cucamonga",
    state: "CA",
  },
  {
    name: "University",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Spokane Valley",
    state: "WA",
  },
  {
    name: "University City",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "University Irvine",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "University Prep",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Redding",
    state: "CA",
  },
  {
    name: "University Prep-Victorville",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Victorville",
    state: "CA",
  },
  {
    name: "Vacaville",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Vacaville",
    state: "CA",
  },
  {
    name: "Valencia (Placentia)",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Placentia",
    state: "CA",
  },
  {
    name: "Valencia (Valencia)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Valencia",
    state: "CA",
  },
  {
    name: "Valley Christian (Cerritos)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Cerritos",
    state: "CA",
  },
  {
    name: "Valley View",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Moreno Valley",
    state: "CA",
  },
  {
    name: "Vasquez",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Acton",
    state: "CA",
  },
  {
    name: "Venice",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Ventura",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Ventura",
    state: "CA",
  },
  {
    name: "Verrado",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Buckeye",
    state: "AZ",
  },
  {
    name: "Viewpoint",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Calabasas",
    state: "CA",
  },
  {
    name: "Villa Park",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Villa Park",
    state: "CA",
  },
  {
    name: "Vintage",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Napa",
    state: "CA",
  },
  {
    name: "Virgin Valley",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Mesquite",
    state: "NV",
  },
  {
    name: "Vista Del Lago",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Moreno Valley",
    state: "CA",
  },
  {
    name: "Vista Murrieta",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Murrieta",
    state: "CA",
  },
  {
    name: "Walnut",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Walnut",
    state: "CA",
  },
  {
    name: "Warren",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Downey",
    state: "CA",
  },
  {
    name: "Warrenton",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Warrenton",
    state: "OR",
  },
  {
    name: "Webb",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Claremont",
    state: "CA",
  },
  {
    name: "West Chicago (Wheaton Academy)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "West Chicago",
    state: "IL",
  },
  {
    name: "West Hills",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Santee",
    state: "CA",
  },
  {
    name: "West Ranch",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Stevenson Ranch",
    state: "CA",
  },
  {
    name: "West Salem",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Salem",
    state: "OR",
  },
  {
    name: "West Torrance",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Torrance",
    state: "CA",
  },
  {
    name: "Westby",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Westby",
    state: "WI",
  },
  {
    name: "Westlake",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Westlake Village",
    state: "CA",
  },
  {
    name: "Westminster",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.b,
    city: "Westminster",
    state: "CA",
  },
  {
    name: "Westridge (G)",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Pasadena",
    state: "CA",
  },
  {
    name: "Westview",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "San Diego",
    state: "CA",
  },
  {
    name: "Whitney",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Cerritos",
    state: "CA",
  },
  {
    name: "Whittier",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Whittier",
    state: "CA",
  },
  {
    name: "Whittier Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "La Habra",
    state: "CA",
  },
  {
    name: "Wichita Falls Memorial",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Wichita Falls",
    state: "TX",
  },
  {
    name: "Will C. Wood",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Vacaville",
    state: "CA",
  },
  {
    name: "Wilson (Long Beach)",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Long Beach",
    state: "CA",
  },
  {
    name: "Windward",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Los Angeles",
    state: "CA",
  },
  {
    name: "Woodbridge",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.a,
    city: "Irvine",
    state: "CA",
  },
  {
    name: "Woodcreek",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.b,
    city: "Roseville",
    state: "CA",
  },
  {
    name: "Woodcrest Christian",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Riverside",
    state: "CA",
  },
  {
    name: "Woodlake",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Woodlake",
    state: "CA",
  },
  {
    name: "Woodside",
    raceDay: "Friday",
    division: divisions.three,
    varsityHeat: heats.a,
    city: "Woodside",
    state: "CA",
  },
  {
    name: "Xavier College Preparatory",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.b,
    city: "Phoenix",
    state: "AZ",
  },
  {
    name: "Yorba Linda",
    raceDay: "Saturday",
    division: divisions.two,
    varsityHeat: heats.a,
    city: "Yorba Linda",
    state: "CA",
  },
  {
    name: "Yosemite",
    raceDay: "Friday",
    division: divisions.four,
    varsityHeat: heats.a,
    city: "Oakhurst",
    state: "CA",
  },
  {
    name: "Yucaipa",
    raceDay: "Saturday",
    division: divisions.one,
    varsityHeat: heats.b,
    city: "Yucaipa",
    state: "CA",
  },
]
  .map((team, index) => ({
    ...team,
    id: index,
  }))
  .sort((a, b) => a.name.localeCompare(b.name));
